import { AssetsMap } from '../../../../configs/AssetsMap';

export const rarityColors: Record<string, string> = {
    COMMON: '#9e9e9e',
    RARE: '#2196f3',
    EPIC: '#a855f7',
    LEGENDARY: '#ff9800',
    MYTHIC: '#ef4444',
};

export const rarityTranslation: Record<string, string> = {
    COMMON: 'ОБЫЧНЫЙ',
    RARE: 'РЕДКИЙ',
    EPIC: 'ЭПИЧЕСКИЙ',
    LEGENDARY: 'ЛЕГЕНДАРНЫЙ',
    MYTHIC: 'МИФИЧЕСКИЙ',
};

export const itemTypeTranslation: Record<string, string> = {
    WEAPONS: 'МЕЧ',
    HELMETS: 'ШЛЕМ',
    ARMOR: 'ДОСПЕХ',
    SHIELDS: 'ЩИТ',
    SHOULDERS: 'НАПЛЕЧНИКИ',
    PANTS: 'ПОНОЖИ',
    BOOTS: 'ОБУВЬ',
};

export const getPluralItems = (count: number): string => {
    const mod10 = count % 10;
    const mod100 = count % 100;
    if (mod100 >= 11 && mod100 <= 19) {
        return `${count} ПРЕДМЕТОВ`;
    }
    if (mod10 === 1) {
        return `${count} ПРЕДМЕТ`;
    }
    if (mod10 >= 2 && mod10 <= 4) {
        return `${count} ПРЕДМЕТА`;
    }
    return `${count} ПРЕДМЕТОВ`;
};

export const categories = [
    { id: 'ALL', label: '🎒' },
    { id: 'WEAPONS', label: '⚔️' },
    { id: 'HELMETS', label: '🪖' },
    { id: 'ARMOR', label: '👕' },
    { id: 'SHIELDS', label: '🛡️' },
    { id: 'SHOULDERS', label: '肩' },
    { id: 'PANTS', label: '👖' },
    { id: 'BOOTS', label: '🥾' },
];

export const categoryIcons: Record<string, string> = {
    ALL: AssetsMap.UI.TAB_ARSENAL,
    WEAPONS: AssetsMap.UI.BLUEPRINT_WEAPON,
    HELMETS: AssetsMap.UI.BLUEPRINT_HELMET,
    ARMOR: AssetsMap.UI.BLUEPRINT_ARMOR,
    SHIELDS: AssetsMap.UI.BLUEPRINT_SHIELD,
    BOOTS: AssetsMap.UI.BLUEPRINT_BOOTS,
    PANTS: AssetsMap.UI.BLUEPRINT_PANTS,
    SHOULDERS: AssetsMap.UI.BLUEPRINT_SHOULDERS,
};

export const getStatTheme = (label: string) => {
    const upper = label.toUpperCase();
    if (upper.includes('ЗАЩИТА') || upper.includes('DEFENSE')) {
        return {
            border: '1.5px solid rgba(96, 165, 250, 0.65)',
            bg: 'rgba(16, 24, 40, 0.95)',
            shadow: '0 8px 24px rgba(59, 130, 246, 0.25)',
            textColor: '#60a5fa',
        };
    }
    if (upper.includes('ЗДОРОВЬЕ') || upper.includes('HP') || upper.includes('HEALTH')) {
        return {
            border: '1.5px solid rgba(248, 113, 113, 0.65)',
            bg: 'rgba(40, 16, 16, 0.95)',
            shadow: '0 8px 24px rgba(239, 68, 68, 0.25)',
            textColor: '#f87171',
        };
    }
    if (upper.includes('ПРОБИВАНИЕ') || upper.includes('PENETRATION') || upper.includes('ПРОБИВ')) {
        return {
            border: '1.5px solid rgba(192, 132, 252, 0.65)',
            bg: 'rgba(32, 16, 40, 0.95)',
            shadow: '0 8px 24px rgba(168, 85, 247, 0.25)',
            textColor: '#c084fc',
        };
    }
    return {
        border: '1.5px solid rgba(240, 192, 64, 0.65)',
        bg: 'rgba(28, 20, 14, 0.95)',
        shadow: '0 8px 24px rgba(240, 192, 64, 0.25)',
        textColor: '#fcd34d',
    };
};

export const styles: Record<string, React.CSSProperties> = {
    screenContainer: {
        position: 'absolute',
        inset: 0,
        background: 'transparent',
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
        padding: '30px 40px',
        color: '#fff',
        fontFamily: "'Cinzel', serif",
        userSelect: 'none',
        pointerEvents: 'auto',
    },
    bgOverlay: {
        position: 'absolute',
        inset: 0,
        background: `#0d0a08 url("${AssetsMap.BACKGROUNDS.FORGE}") no-repeat center/cover`,
        filter: 'brightness(0.85)',
        zIndex: 0,
        pointerEvents: 'none',
    },
    header: {
        position: 'relative',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '35px',
        zIndex: 10000,
        borderBottom: '1.5px solid rgba(240, 192, 64, 0.25)',
        paddingBottom: '20px',
    },
    headerTitleGroup: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        flex: 1,
    },
    mainTitle: {
        fontSize: '36px',
        fontWeight: 950,
        background: 'linear-gradient(180deg, #ffffff 0%, #f0c040 100%)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        textShadow: '0 4px 12px rgba(0,0,0,0.6)',
        letterSpacing: '3px',
        margin: 0,
    },
    subTitle: {
        fontSize: '13px',
        color: '#a08560',
        fontWeight: 800,
        letterSpacing: '2px',
        marginTop: '6px',
    },
    mainContent: {
        position: 'relative',
        flex: 1,
        display: 'flex',
        gap: '40px',
        zIndex: 10,
        height: 'calc(100% - 120px)',
    },
    arsenalPanel: {
        width: '380px',
        background: 'rgba(18, 14, 11, 0.85)',
        borderRadius: '24px',
        border: '1.5px solid rgba(240, 192, 64, 0.35)',
        backdropFilter: 'blur(20px)',
        padding: '25px',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '0 15px 40px rgba(0,0,0,0.7)',
    },
    panelHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '15px',
        fontSize: '16px',
        fontWeight: 900,
        fontFamily: "'Cinzel', serif",
        letterSpacing: '1.5px',
        color: '#f0c040',
    },
    categoryRow: {
        display: 'flex',
        justifyContent: 'space-between',
        gap: '6px',
        marginBottom: '15px',
        paddingBottom: '15px',
        borderBottom: '1px solid rgba(255,255,255,0.08)',
    },
    categoryBtn: {
        width: '40px',
        height: '40px',
        borderRadius: '8px',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'all 0.2s',
        flexShrink: 0,
    },
    inventoryGrid: {
        flex: 1,
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gridAutoRows: '95px',
        gap: '12px',
        overflowY: 'auto',
        paddingRight: '5px',
    },
    itemCard: {
        borderRadius: '14px',
        cursor: 'pointer',
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '12px',
        border: '1px solid rgba(255,255,255,0.08)',
        transition: 'all 0.2s',
    },
    itemImg: {
        width: '90%',
        height: '90%',
        objectFit: 'contain',
    },
    itemLvlBadge: {
        position: 'absolute',
        bottom: '6px',
        right: '6px',
        background: 'rgba(10, 7, 5, 0.95)',
        fontSize: '12px',
        fontWeight: 800,
        padding: '2px 8px',
        borderRadius: '6px',
        fontFamily: "'Cinzel', serif",
        letterSpacing: '0.5px',
        boxShadow: '0 2px 6px rgba(0,0,0,0.5)',
    },
    reforgeBadge: {
        position: 'absolute',
        top: '6px',
        left: '6px',
        background: 'rgba(168, 85, 247, 0.95)',
        border: '1.5px solid rgba(168, 85, 247, 0.65)',
        color: '#fff',
        fontSize: '11px',
        fontWeight: 800,
        padding: '2px 6px',
        borderRadius: '6px',
        boxShadow: '0 2px 6px rgba(0,0,0,0.5)',
    },
    sortSelector: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 15,
        paddingTop: 15,
        borderTop: '1px solid rgba(255,255,255,0.05)',
    },
    dropdown: {
        background: '#15100c',
        border: '1.5px solid rgba(240, 192, 64, 0.3)',
        borderRadius: 8,
        color: '#fff',
        padding: '6px 12px',
        fontSize: 13,
        fontWeight: 800,
        outline: 'none',
        cursor: 'pointer',
        fontFamily: "'Cinzel', serif",
    },
    arsenalActionsRow: {
        display: 'flex',
        gap: 12,
        marginTop: 15,
    },
    circularActionBtn: {
        flex: 1,
        height: '42px',
        background: 'linear-gradient(180deg, rgba(25, 20, 15, 0.85) 0%, rgba(15, 10, 5, 0.95) 100%)',
        border: '1.5px solid rgba(240, 192, 64, 0.45)',
        borderRadius: '21px',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '0 15px',
        gap: '8px',
        transition: 'all 0.2s ease',
        backdropFilter: 'blur(10px)',
    },
    circularBtnTitle: {
        fontSize: '13px',
        fontWeight: 900,
        color: '#f0c040',
        fontFamily: "'Cinzel', serif",
        letterSpacing: '1.5px',
    },
    anvilArea: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'flex-end',
        position: 'relative',
        paddingBottom: '50px',
    },
    glowOverlay: {
        position: 'absolute',
        inset: 0,
        zIndex: 10,
        pointerEvents: 'none',
    },
    spark: {
        position: 'absolute',
        width: '5px',
        height: '5px',
        background: '#ff6600',
        borderRadius: '50%',
        boxShadow: '0 0 10px #ffcc00',
    },
    levelRoadContainer: {
        display: 'flex',
        justifyContent: 'space-between',
        width: '95%',
        position: 'relative',
        marginBottom: '55px',
        padding: '0 10px',
    },
    levelRoadLine: {
        position: 'absolute',
        top: '20px',
        left: '20px',
        right: '20px',
        height: '2px',
        background: 'rgba(255,255,255,0.15)',
        zIndex: 0,
    },
    levelDotWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        zIndex: 1,
        width: 40,
    },
    levelDiamond: {
        width: 28,
        height: 28,
        transform: 'rotate(45deg)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'default',
        borderRadius: 4,
    },
    levelDiamondText: {
        transform: 'rotate(-45deg)',
        fontSize: '9px',
        fontWeight: 900,
        fontFamily: "'Cinzel', serif",
    },
    currentIndicatorLabel: {
        fontSize: 11,
        color: '#60a5fa',
        fontWeight: 900,
        textTransform: 'uppercase',
        letterSpacing: '1px',
        textShadow: '0 0 8px rgba(96,165,250,0.5)',
        whiteSpace: 'nowrap',
    },
    statsBadgesRow: {
        display: 'flex',
        gap: 15,
        marginBottom: '30px',
        width: '90%',
        justifyContent: 'center',
    },
    statBadgeCard: {
        background: 'rgba(28, 20, 14, 0.95)',
        border: '1.5px solid rgba(240, 192, 64, 0.65)',
        borderRadius: '16px',
        padding: '12px 18px',
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        flex: 1,
        maxWidth: '180px',
        boxShadow: '0 8px 24px rgba(240, 192, 64, 0.25)',
        backdropFilter: 'blur(10px)',
    },
    statBadgeLabel: {
        fontSize: '11px',
        color: '#f0c040',
        fontWeight: 800,
        letterSpacing: '1px',
    },
    statBadgeVal: {
        fontSize: '16px',
        fontWeight: 900,
        color: '#fff',
    },
    statBadgeDiff: {
        fontSize: '14px',
        color: '#4ade80',
        fontWeight: 900,
        marginLeft: '4px',
    },
    bottomNote: {
        fontSize: '13px',
        opacity: 0.9,
        color: '#d8c0a0',
        textAlign: 'center',
        fontWeight: 700,
        textShadow: '0 2px 4px rgba(0,0,0,0.85)',
    },
    statsPanel: {
        width: '420px',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    itemDetailsCard: {
        flex: 1,
        background: 'rgba(18, 14, 11, 0.85)',
        borderRadius: '24px',
        border: '1.5px solid rgba(240, 192, 64, 0.35)',
        backdropFilter: 'blur(20px)',
        padding: '25px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        boxShadow: '0 15px 40px rgba(0,0,0,0.7)',
    },
    itemSubtitle: {
        fontSize: 13,
        fontWeight: 900,
        letterSpacing: '1.5px',
        fontFamily: "'Cinzel', serif",
    },
    itemName: {
        fontSize: '26px',
        margin: '5px 0 20px 0',
        textAlign: 'center',
        fontFamily: "'Cinzel', serif",
        fontWeight: 900,
        color: '#fff',
        letterSpacing: '1px',
    },
    itemShowcaseContainer: {
        width: '180px',
        height: '180px',
        background: 'radial-gradient(circle, rgba(20, 15, 10, 0.85) 0%, rgba(5, 5, 5, 0.98) 100%)',
        borderRadius: '50%',
        border: '1.5px solid rgba(240, 192, 64, 0.35)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        overflow: 'hidden',
        boxShadow: '0 10px 30px rgba(0,0,0,0.7), inset 0 0 20px rgba(240, 192, 64, 0.1)',
        margin: '15px auto',
    },
    progressBarBg: {
        width: '100%',
        height: '6px',
        background: 'rgba(255, 255, 255, 0.1)',
        borderRadius: '3px',
        overflow: 'hidden',
        marginTop: '6px',
    },
    progressBarFill: {
        height: '100%',
        background: 'linear-gradient(90deg, #3b82f6 0%, #60a5fa 100%)',
        borderRadius: '3px',
        transition: 'width 0.3s ease',
        boxShadow: '0 0 8px rgba(96, 165, 250, 0.5)',
    },
    statsListHeader: {
        fontSize: 12,
        letterSpacing: '2px',
        color: '#f0c040',
        margin: '0 0 12px 0',
        fontWeight: 900,
        fontFamily: "'Cinzel', serif",
    },
    statsList: {
        display: 'flex',
        flexDirection: 'column',
    },
    resourcesCostCard: {
        background: 'rgba(18, 14, 11, 0.85)',
        borderRadius: '24px',
        border: '1.5px solid rgba(240, 192, 64, 0.35)',
        padding: '25px',
        boxShadow: '0 15px 40px rgba(0,0,0,0.7)',
        backdropFilter: 'blur(20px)',
    },
    resourcesGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(80px, 1fr))',
        gap: '10px',
        marginBottom: '20px',
        width: '100%',
    },
    resourceReqItem: {
        background: 'rgba(10, 8, 6, 0.9)',
        border: '1.5px solid rgba(240,192,64,0.35)',
        borderRadius: '14px',
        padding: '12px 8px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '6px',
        transition: 'border-color 0.2s',
    },
    resIcon: {
        width: '32px',
        height: '32px',
        objectFit: 'contain',
    },
    upgradeBtn: {
        width: '100%',
        border: 'none',
        borderRadius: '12px',
        fontWeight: 950,
        fontFamily: "'Cinzel', serif",
        transition: 'all 0.2s',
    },
    emptyDetails: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'rgba(18, 14, 11, 0.85)',
        borderRadius: '24px',
        border: '1.5px solid rgba(240, 192, 64, 0.35)',
        padding: 40,
        textAlign: 'center',
        backdropFilter: 'blur(20px)',
    },
    modalOverlay: {
        position: 'absolute',
        inset: 0,
        background: 'rgba(0,0,0,0.85)',
        backdropFilter: 'blur(5px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
    },
    modalContent: {
        width: '380px',
        background: 'rgba(15, 10, 8, 0.95)',
        border: '2px solid rgba(240, 192, 64, 0.35)',
        borderRadius: 24,
        padding: 30,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        textAlign: 'center',
        boxShadow: '0 25px 60px rgba(0,0,0,0.9)',
        backdropFilter: 'blur(15px)',
    },
    modalActionBtn: {
        flex: 1,
        padding: '14px 0',
        borderRadius: 12,
        border: 'none',
        cursor: 'pointer',
        fontSize: 13,
        fontWeight: 900,
        fontFamily: "'Cinzel', serif",
    },
};
