import { IEquipmentStats } from './types';

export const armor: Record<string, IEquipmentStats> = {
    ragged_tunic: {
        id: 'ragged_tunic',
        name: 'Рваная Туника Скитальца',
        priceGold: 90,
        requiredLevel: 1,
        image: '/assets/images/items/armor/ragged_tunic.webp',
        rarity: 'COMMON',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        defenseBonus: 3,
        hpBonus: 30,
        desc: 'Старая туника, которая едва держится на плечах.',
    },
    starter_armor: {
        id: 'starter_armor',
        name: 'Ученический Доспех',
        priceGold: 250,
        requiredLevel: 1,
        image: '/assets/images/items/armor/starter_armor.webp',
        rarity: 'COMMON',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        textureKey: 'armor_leather',
        defenseBonus: 10,
        hpBonus: 100,
        desc: 'Легкая броня для начинающих воинов.',
    },
    armor_ranger: {
        id: 'armor_ranger',
        name: 'Кожаная Куртка Рейнджера',
        defenseBonus: 18,
        hpBonus: 180,
        rarity: 'RARE',
        priceGold: 3000,
        requiredLevel: 10,
        image: '/assets/images/items/armor/spiked_leather.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Надежная куртка, сшитая из качественной кожи лесных зверей.',
    },
    armor_forest: {
        id: 'armor_forest',
        name: 'Шкура Северного Медведя',
        defenseBonus: 38,
        hpBonus: 380,
        rarity: 'RARE',
        priceGold: 8000,
        requiredLevel: 15,
        image: '/assets/images/items/armor/hunter_furs.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Плотная меховая шкура, согревающая в самые лютые морозы.',
    },
    armor_ice: {
        id: 'armor_ice',
        name: 'Жилет Шипастой Кожи',
        defenseBonus: 55,
        hpBonus: 550,
        rarity: 'RARE',
        priceGold: 18000,
        requiredLevel: 18,
        image: '/assets/images/items/armor/spiked_leather.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Шипы на этом жилете заставляют врагов держаться подальше.',
    },
    armor_iron: {
        id: 'armor_iron',
        name: 'Кольчуга Ветерана',
        defenseBonus: 75,
        hpBonus: 750,
        rarity: 'EPIC',
        priceGem: 400,
        requiredLevel: 28,
        image: '/assets/images/items/armor/chainmail.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Закаленная в сотнях сражений кольчуга.',
    },
    armor_steam: {
        id: 'armor_steam',
        name: 'Броня Парового Механика',
        defenseBonus: 160,
        hpBonus: 1600,
        rarity: 'EPIC',
        priceGem: 900,
        requiredLevel: 40,
        image: '/assets/images/items/armor/armor_steampunk.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Сложная система трубок и клапанов поддерживает выносливость.',
    },
    armor_fire: {
        id: 'armor_fire',
        name: 'Панцирь Золотого Льва',
        defenseBonus: 260,
        hpBonus: 2600,
        rarity: 'LEGENDARY',
        priceGem: 1800,
        requiredLevel: 52,
        image: '/assets/images/items/armor/armor_lion.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Пропитан яростью и величием солнечного льва.',
    },
    armor_void: {
        id: 'armor_void',
        name: 'Одеяние Пылающего Феникса',
        defenseBonus: 380,
        hpBonus: 3800,
        rarity: 'LEGENDARY',
        priceGem: 3200,
        requiredLevel: 58,
        image: '/assets/images/items/armor/armor_phoenix.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Дарует бессмертие духа и защиту от любых температур.',
    },
    armor_bone: {
        id: 'armor_bone',
        name: 'Кираса Повелителя Костей',
        defenseBonus: 500,
        hpBonus: 5000,
        rarity: 'MYTHIC',
        priceGem: 5500,
        requiredLevel: 70,
        image: '/assets/images/items/armor/armor_bone.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Сделана из зачарованных костей древних воинов.',
    },
    tunika_lesnogo_uchenika: {
        id: 'tunika_lesnogo_uchenika',
        name: 'Туника Лесного Ученика',
        defenseBonus: 15,
        hpBonus: 150,
        rarity: 'COMMON',
        priceGold: 500,
        requiredLevel: 3,
        image: '/assets/images/items/armor/tunika_lesnogo_uchenika.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Простая туника, сшитая из грубого льна и украшенная листьями.',
    },
    steganyy_dospeh_opolchenca: {
        id: 'steganyy_dospeh_opolchenca',
        name: 'Стёганый Доспех Ополченца',
        defenseBonus: 25,
        hpBonus: 250,
        rarity: 'COMMON',
        priceGold: 1200,
        requiredLevel: 5,
        image: '/assets/images/items/armor/steganyy_dospeh_opolchenca.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Многослойный стеганый доспех для базовой защиты городского ополчения.',
    },
    kirasa_mednogo_straja: {
        id: 'kirasa_mednogo_straja',
        name: 'Кираса Медного Стража',
        defenseBonus: 45,
        hpBonus: 450,
        rarity: 'RARE',
        priceGold: 6000,
        requiredLevel: 12,
        image: '/assets/images/items/armor/kirasa_mednogo_straja.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Медный доспех, покрытый тонким слоем патины.',
    },
    dospeh_rechnogo_pirata: {
        id: 'dospeh_rechnogo_pirata',
        name: 'Доспех Речного Пирата',
        defenseBonus: 70,
        hpBonus: 700,
        rarity: 'RARE',
        priceGem: 500,
        requiredLevel: 16,
        image: '/assets/images/items/armor/dospeh_rechnogo_pirata.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Кожаная кираса, укрепленная металлическими пластинами и пропахшая тиной.',
    },
    pancir_bolotnogo_trollya: {
        id: 'pancir_bolotnogo_trollya',
        name: 'Панцирь Болотного Тролля',
        defenseBonus: 95,
        hpBonus: 950,
        rarity: 'RARE',
        priceGold: 22000,
        requiredLevel: 19,
        image: '/assets/images/items/armor/pancir_bolotnogo_trollya.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Сверхпрочные костяные наросты болотного чудовища.',
    },
    bronya_pepelnogo_maga: {
        id: 'bronya_pepelnogo_maga',
        name: 'Мантия Звездного Мага',
        defenseBonus: 130,
        hpBonus: 1300,
        rarity: 'EPIC',
        priceGold: 30000,
        requiredLevel: 26,
        image: '/assets/images/items/armor/mantia_zvezdnogo_maga.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Тканевая мантия, сотканная из астральной материи и сияния далеких галактик.',
    },
    laty_kamennogo_straja: {
        id: 'laty_kamennogo_straja',
        name: 'Латы Каменного Стража',
        defenseBonus: 180,
        hpBonus: 1800,
        rarity: 'EPIC',
        priceGem: 550,
        requiredLevel: 32,
        image: '/assets/images/items/armor/laty_kamennogo_straja.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Тяжелый каменный панцирь, высеченный из монолитной скалы.',
    },
    dospeh_grozovogo_titana: {
        id: 'dospeh_grozovogo_titana',
        name: 'Доспех Грозового Титана',
        defenseBonus: 240,
        hpBonus: 2400,
        rarity: 'EPIC',
        priceGold: 45000,
        requiredLevel: 38,
        image: '/assets/images/items/armor/dospeh_grozovogo_titana.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Кираса, выкованная в кузнях бури, заряжена разрушительной энергией молний.',
    },
    bronya_kostyanogo_jneca: {
        id: 'bronya_kostyanogo_jneca',
        name: 'Ледяной Доспех Морозного Стража',
        defenseBonus: 310,
        hpBonus: 3100,
        rarity: 'EPIC',
        priceGem: 1100,
        requiredLevel: 44,
        image: '/assets/images/items/armor/dospeh_moroznogo_straja.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Тяжелые латы, выкованные из векового льда северных пустошей, сковывающие врагов морозом.',
    },
    kirasa_vechnogo_plameni: {
        id: 'kirasa_vechnogo_plameni',
        name: 'Кираса Вечного Пламени',
        defenseBonus: 460,
        hpBonus: 4600,
        rarity: 'MYTHIC',
        priceGem: 6000,
        requiredLevel: 66,
        image: '/assets/images/items/armor/kirasa_vechnogo_plameni.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Легендарные доспехи, объятые неугасающим первородным огнем.',
    },
};
