import { IEquipmentStats } from './types';

export const armor: Record<string, IEquipmentStats> = {
    ragged_tunic: {
        id: 'ragged_tunic',
        name: 'Рваная Туника Скитальца',
        priceGold: 200,
        requiredLevel: 1,
        image: '/assets/images/items/armor/ragged_tunic.webp',
        rarity: 'COMMON',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        defenseBonus: 3,
        hpBonus: 30,
        desc: 'Старая туника, которая едва держится на плечах.',
    },
    starter_armor: {
        id: 'starter_armor',
        name: 'Ученический Доспех',
        priceGold: 600,
        requiredLevel: 3,
        image: '/assets/images/items/armor/starter_armor.webp',
        rarity: 'COMMON',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        textureKey: 'armor_leather',
        defenseBonus: 10,
        hpBonus: 100,
        desc: 'Легкая броня для начинающих воинов.',
    },
    armor_ranger: {
        id: 'armor_ranger',
        name: 'Кожаная Куртка Рейнджера',
        defenseBonus: 18,
        hpBonus: 180,
        rarity: 'RARE',
        priceGold: 3000,
        requiredLevel: 10,
        image: '/assets/images/items/armor/spiked_leather.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Надежная куртка, сшитая из качественной кожи лесных зверей.',
    },
    armor_forest: {
        id: 'armor_forest',
        name: 'Шкура Северного Медведя',
        defenseBonus: 38,
        hpBonus: 380,
        rarity: 'RARE',
        priceGold: 8000,
        requiredLevel: 15,
        image: '/assets/images/items/armor/hunter_furs.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Плотная меховая шкура, согревающая в самые лютые морозы.',
    },
    armor_ice: {
        id: 'armor_ice',
        name: 'Жилет Шипастой Кожи',
        defenseBonus: 55,
        hpBonus: 550,
        rarity: 'RARE',
        priceGold: 18000,
        requiredLevel: 18,
        image: '/assets/images/items/armor/spiked_leather.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Шипы на этом жилете заставляют врагов держаться подальше.',
    },
    armor_iron: {
        id: 'armor_iron',
        name: 'Кольчуга Ветерана',
        defenseBonus: 75,
        hpBonus: 750,
        rarity: 'EPIC',
        priceGem: 400,
        requiredLevel: 28,
        image: '/assets/images/items/armor/chainmail.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Закаленная в сотнях сражений кольчуга.',
    },
    armor_steam: {
        id: 'armor_steam',
        name: 'Броня Парового Механика',
        defenseBonus: 160,
        hpBonus: 1600,
        rarity: 'EPIC',
        priceGem: 900,
        requiredLevel: 40,
        image: '/assets/images/items/armor/armor_steampunk.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Сложная система трубок и клапанов поддерживает выносливость.',
    },
    armor_fire: {
        id: 'armor_fire',
        name: 'Панцирь Золотого Льва',
        defenseBonus: 260,
        hpBonus: 2600,
        rarity: 'LEGENDARY',
        priceGem: 1800,
        requiredLevel: 52,
        image: '/assets/images/items/armor/armor_lion.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Пропитан яростью и величием солнечного льва.',
    },
    armor_void: {
        id: 'armor_void',
        name: 'Одеяние Пылающего Феникса',
        defenseBonus: 380,
        hpBonus: 3800,
        rarity: 'LEGENDARY',
        priceGem: 3200,
        requiredLevel: 58,
        image: '/assets/images/items/armor/armor_phoenix.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Дарует бессмертие духа и защиту от любых температур.',
    },
    armor_bone: {
        id: 'armor_bone',
        name: 'Кираса Повелителя Костей',
        defenseBonus: 500,
        hpBonus: 5000,
        rarity: 'MYTHIC',
        priceGem: 5500,
        requiredLevel: 70,
        image: '/assets/images/items/armor/armor_bone.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Сделана из зачарованных костей древних воинов.',
    },
};
