import { IEquipmentStats } from './types';

export const armor: Record<string, IEquipmentStats> = {
    armor_fire: {
        id: 'armor_fire',
        name: 'Панцирь Золотого Льва',
        defenseBonus: 40,
        hpBonus: 600,
        rarity: 'LEGENDARY',
        priceGem: 2500,
        image: '/assets/images/items/armor/armor_lion.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Пропитан яростью и величием солнечного льва.',
    },
    armor_forest: {
        id: 'armor_forest',
        name: 'Шкура Северного Медведя',
        defenseBonus: 15,
        hpBonus: 200,
        rarity: 'RARE',
        priceGold: 8000,
        image: '/assets/images/items/armor/hunter_furs.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Плотная меховая шкура, согревающая в самые лютые морозы.',
    },
    armor_iron: {
        id: 'armor_iron',
        name: 'Кольчуга Ветерана',
        defenseBonus: 30,
        hpBonus: 400,
        rarity: 'EPIC',
        priceGem: 800,
        image: '/assets/images/items/armor/chainmail.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Закаленная в сотнях сражений кольчуга.',
    },
    armor_bone: {
        id: 'armor_bone',
        name: 'Кираса Повелителя Костей',
        defenseBonus: 35,
        hpBonus: 500,
        rarity: 'MYTHIC',
        priceGem: 1000,
        image: '/assets/images/items/armor/armor_bone.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Сделана из зачарованных костей древних воинов.',
    },
    armor_ice: {
        id: 'armor_ice',
        name: 'Жилет Шипастой Кожи',
        defenseBonus: 25,
        hpBonus: 350,
        rarity: 'RARE',
        priceGold: 15000,
        image: '/assets/images/items/armor/spiked_leather.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Шипы на этом жилете заставляют врагов держаться подальше.',
    },
    armor_steam: {
        id: 'armor_steam',
        name: 'Броня Парового Механика',
        defenseBonus: 45,
        hpBonus: 700,
        rarity: 'EPIC',
        priceGem: 1200,
        image: '/assets/images/items/armor/armor_steampunk.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Сложная система трубок и клапанов поддерживает выносливость.',
    },
    armor_void: {
        id: 'armor_void',
        name: 'Одеяние Пылающего Феникса',
        defenseBonus: 100,
        hpBonus: 1500,
        rarity: 'LEGENDARY',
        priceGem: 3000,
        image: '/assets/images/items/armor/armor_phoenix.webp',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        desc: 'Дарует бессмертие духа и защиту от любых температур.',
    },
    ragged_tunic: {
        id: 'ragged_tunic',
        name: 'Рваная Туника Скитальца',
        priceGold: 200,
        image: '/assets/images/items/armor/ragged_tunic.webp',
        rarity: 'COMMON',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        defenseBonus: 3,
        hpBonus: 30,
        desc: 'Старая туника, которая едва держится на плечах.',
    },
    starter_armor: {
        id: 'starter_armor',
        name: 'Ученический Доспех',
        priceGold: 0,
        image: '/assets/images/items/armor/starter_armor.webp',
        rarity: 'COMMON',
        mainTab: 'ARSENAL',
        subTab: 'ARMOR',
        textureKey: 'armor_leather',
        defenseBonus: 10,
        hpBonus: 100,
        desc: 'Легкая броня для начинающих воинов.',
    },
};
