import { IEquipmentStats } from './types';

export const boots: Record<string, IEquipmentStats> = {
    boots_wanderer: {
        id: 'boots_wanderer',
        name: 'Сапоги Скитальца',
        speedBonus: 0.05,
        hpBonus: 50,
        rarity: 'COMMON',
        priceGold: 500,
        image: '/assets/images/items/boots/boots_1.png',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Потертая, но удобная обувь для долгих странствий.',
    },
    boots_hunter: {
        id: 'boots_hunter',
        name: 'Егерские Сапоги',
        speedBonus: 0.08,
        hpBonus: 150,
        rarity: 'RARE',
        priceGold: 2000,
        image: '/assets/images/items/boots/boots_5.png',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Позволяют бесшумно передвигаться по лесу.',
    },
    boots_chain: {
        id: 'boots_chain',
        name: 'Кольчужные Сапоги',
        defenseBonus: 25,
        hpBonus: 450,
        rarity: 'RARE',
        priceGold: 8000,
        image: '/assets/images/items/boots/boots_6.png',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Идеальный баланс между весом и защитой.',
    },
    boots_iron: {
        id: 'boots_iron',
        name: 'Стальные Сабатоны',
        defenseBonus: 20,
        hpBonus: 300,
        rarity: 'RARE',
        priceGold: 3500,
        image: '/assets/images/items/boots/boots_2.png',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Тяжелая латная защита для ног.',
    },
    boots_rune: {
        id: 'boots_rune',
        name: 'Эфирные Следоходы',
        speedBonus: 0.12,
        hpBonus: 500,
        rarity: 'EPIC',
        priceGem: 450,
        image: '/assets/images/items/boots/boots_3.png',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Магические руны делают походку легкой, как сам эфир.',
    },
    boots_bone: {
        id: 'boots_bone',
        name: 'Поступь Повелителя Мертвых',
        defenseBonus: 45,
        hpBonus: 800,
        rarity: 'MYTHIC',
        priceGem: 950,
        image: '/assets/images/items/boots/boots_4.png',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Каждый шаг пробуждает тени прошлого.',
    },
    boots_paladin: {
        id: 'boots_paladin',
        name: 'Сапоги Солнечного Императора',
        defenseBonus: 85,
        hpBonus: 1600,
        rarity: 'LEGENDARY',
        priceGem: 1800,
        image: '/assets/images/items/boots/boots_7.png',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Величественная броня, сияющая светом тысячи солнц.',
    },
};
