import { IEquipmentStats } from './types';

export const boots: Record<string, IEquipmentStats> = {
    boots_wanderer: {
        id: 'boots_wanderer',
        name: 'Сапоги Скитальца',
        speedBonus: 0.03,
        hpBonus: 40,
        rarity: 'COMMON',
        priceGold: 400,
        requiredLevel: 2,
        image: '/assets/images/items/boots/boots_1.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Потертая, но удобная обувь для долгих странствий.',
    },
    boots_iron: {
        id: 'boots_iron',
        name: 'Стальные Сабатоны',
        defenseBonus: 15,
        hpBonus: 150,
        rarity: 'RARE',
        priceGold: 3000,
        requiredLevel: 10,
        image: '/assets/images/items/boots/boots_2.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Тяжелая латная защита для ног.',
    },
    boots_hunter: {
        id: 'boots_hunter',
        name: 'Егерские Сапоги',
        speedBonus: 0.07,
        hpBonus: 250,
        defenseBonus: 25,
        rarity: 'RARE',
        priceGold: 7000,
        requiredLevel: 14,
        image: '/assets/images/items/boots/boots_5.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Позволяют бесшумно передвигаться по лесу.',
    },
    boots_chain: {
        id: 'boots_chain',
        name: 'Кольчужные Сапоги',
        defenseBonus: 50,
        hpBonus: 500,
        rarity: 'RARE',
        priceGold: 15000,
        requiredLevel: 18,
        image: '/assets/images/items/boots/boots_6.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Идеальный баланс между весом и защитой.',
    },
    boots_rune: {
        id: 'boots_rune',
        name: 'Эфирные Следоходы',
        speedBonus: 0.14,
        hpBonus: 900,
        defenseBonus: 90,
        rarity: 'EPIC',
        priceGem: 650,
        requiredLevel: 35,
        image: '/assets/images/items/boots/boots_3.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Магические руны делают походку легкой, как сам эфир.',
    },
    boots_paladin: {
        id: 'boots_paladin',
        name: 'Сапоги Солнечного Императора',
        defenseBonus: 280,
        hpBonus: 2800,
        speedBonus: 0.08,
        rarity: 'LEGENDARY',
        priceGem: 2000,
        requiredLevel: 55,
        image: '/assets/images/items/boots/boots_7.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Величественная броня, сияющая светом тысячи солнц.',
    },
    boots_bone: {
        id: 'boots_bone',
        name: 'Поступь Повелителя Мертвых',
        defenseBonus: 480,
        hpBonus: 4800,
        speedBonus: 0.2,
        rarity: 'MYTHIC',
        priceGem: 5000,
        requiredLevel: 72,
        image: '/assets/images/items/boots/boots_4.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Каждый шаг пробуждает тени прошлого.',
    },
    kozhanye_porshni: {
        id: 'kozhanye_porshni',
        name: 'Кожаные Поршни',
        hpBonus: 20,
        speedBonus: 0.02,
        rarity: 'COMMON',
        priceGold: 150,
        requiredLevel: 1,
        image: '/assets/images/items/boots/kozhanye_porshni.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Простая самодельная кожаная обувь.',
    },
    boots_bolotnogo_sledopyta: {
        id: 'boots_bolotnogo_sledopyta',
        name: 'Сапоги Болотного Следопыта',
        hpBonus: 60,
        speedBonus: 0.04,
        defenseBonus: 5,
        rarity: 'COMMON',
        priceGold: 900,
        requiredLevel: 4,
        image: '/assets/images/items/boots/boots_bolotnogo_sledopyta.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Пропитанные особым дегтем сапоги для болотных топей.',
    },
    sabatony_zheleznogo_legiona: {
        id: 'sabatony_zheleznogo_legiona',
        name: 'Сабатоны Железного Легиона',
        hpBonus: 420,
        defenseBonus: 42,
        speedBonus: 0.03,
        rarity: 'RARE',
        priceGold: 12000,
        requiredLevel: 16,
        image: '/assets/images/items/boots/sabatony_zheleznogo_legiona.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Тяжелая и надежная обувь легионеров империи.',
    },
    boots_grozovogo_vestnika: {
        id: 'boots_grozovogo_vestnika',
        name: 'Сапоги Грозового Вестника',
        hpBonus: 720,
        defenseBonus: 72,
        speedBonus: 0.09,
        rarity: 'EPIC',
        priceGold: 40000,
        requiredLevel: 28,
        image: '/assets/images/items/boots/boots_grozovogo_vestnika.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Искрятся молниями, увеличивая скорость перемещения.',
    },
    botforty_pustotnogo_ohotnika: {
        id: 'botforty_pustotnogo_ohotnika',
        name: 'Ботфорты Пустотного Охотника',
        hpBonus: 1100,
        defenseBonus: 110,
        speedBonus: 0.12,
        rarity: 'EPIC',
        priceGem: 750,
        requiredLevel: 38,
        image: '/assets/images/items/boots/botforty_pustotnogo_ohotnika.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Сшиты из кожи созданий Бездны, бесшумные и прочные.',
    },
    boots_nekromanta: {
        id: 'boots_nekromanta',
        name: 'Сапоги Некроманта',
        hpBonus: 1350,
        defenseBonus: 135,
        speedBonus: 0.06,
        rarity: 'EPIC',
        priceGold: 50000,
        requiredLevel: 42,
        image: '/assets/images/items/boots/boots_nekromanta.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Овеяны замогильной прохладой, замедляют старение плоти.',
    },
    sabatony_drakoney_cheshui: {
        id: 'sabatony_drakoney_cheshui',
        name: 'Сабатоны Драконьей Чешуи',
        hpBonus: 2400,
        defenseBonus: 240,
        speedBonus: 0.08,
        rarity: 'LEGENDARY',
        priceGem: 1800,
        requiredLevel: 52,
        image: '/assets/images/items/boots/sabatony_drakoney_cheshui.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Кованая обувь, покрытая огнеупорной чешуей красного дракона.',
    },
    postup_zvezdnogo_skitalca: {
        id: 'postup_zvezdnogo_skitalca',
        name: 'Поступь Звёздного Скитальца',
        hpBonus: 4400,
        defenseBonus: 440,
        speedBonus: 0.18,
        rarity: 'MYTHIC',
        priceGem: 5500,
        requiredLevel: 68,
        image: '/assets/images/items/boots/postup_zvezdnogo_skitalca.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Космическая пыль оседает за каждым шагом владельца этих сапог.',
    },
};
