import { IEquipmentStats } from './types';

export const boots: Record<string, IEquipmentStats> = {
    kozhanye_porshni: {
        id: 'kozhanye_porshni',
        name: 'Кожаные Поршни',
        requiredLevel: 1,
        rarity: 'COMMON',
        defenseBonus: 5,
        hpBonus: 55,
        speedBonus: 0.02,
        priceGold: 1500,
        image: '/assets/images/items/boots/kozhanye_porshni.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Простая самодельная кожаная обувь.',
    },

    boots_wanderer: {
        id: 'boots_wanderer',
        name: 'Сапоги Скитальца',
        requiredLevel: 3,
        rarity: 'COMMON',
        defenseBonus: 6,
        hpBonus: 66,
        speedBonus: 0.03,
        priceGem: 15,
        image: '/assets/images/items/boots/boots_1.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Потертая, но удобная обувь для долгих странствий.',
    },

    boots_bolotnogo_sledopyta: {
        id: 'boots_bolotnogo_sledopyta',
        name: 'Сапоги Болотного Следопыта',
        requiredLevel: 10,
        rarity: 'COMMON',
        defenseBonus: 14,
        hpBonus: 154,
        speedBonus: 0.04,
        priceGold: 5500,
        image: '/assets/images/items/boots/boots_bolotnogo_sledopyta.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Пропитанные особым дегтем сапоги для болотных топей.',
    },

    boots_hunter: {
        id: 'boots_hunter',
        name: 'Егерские Сапоги',
        requiredLevel: 11,
        rarity: 'RARE',
        defenseBonus: 15,
        hpBonus: 165,
        speedBonus: 0.07,
        priceGem: 55,
        image: '/assets/images/items/boots/boots_5.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Позволяют бесшумно передвигаться по лесу.',
    },

    boots_iron: {
        id: 'boots_iron',
        name: 'Стальные Сабатоны',
        requiredLevel: 16,
        rarity: 'RARE',
        defenseBonus: 22,
        hpBonus: 242,
        speedBonus: 0.03,
        priceGold: 15000,
        image: '/assets/images/items/boots/boots_2.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Тяжелая латная защита для ног.',
    },

    sabatony_zheleznogo_legiona: {
        id: 'sabatony_zheleznogo_legiona',
        name: 'Сабатоны Железного Легиона',
        requiredLevel: 22,
        rarity: 'RARE',
        defenseBonus: 31,
        hpBonus: 341,
        speedBonus: 0.03,
        priceGem: 150,
        image: '/assets/images/items/boots/sabatony_zheleznogo_legiona.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Тяжелая и надежная обувь легионеров империи.',
    },

    boots_chain: {
        id: 'boots_chain',
        name: 'Кольчужные Сапоги',
        requiredLevel: 27,
        rarity: 'RARE',
        defenseBonus: 39,
        hpBonus: 429,
        speedBonus: 0.05,
        priceGold: 35000,
        image: '/assets/images/items/boots/boots_6.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Идеальный баланс между весом и защитой.',
    },

    boots_grozovogo_vestnika: {
        id: 'boots_grozovogo_vestnika',
        name: 'Сапоги Грозового Вестника',
        requiredLevel: 28,
        rarity: 'EPIC',
        defenseBonus: 40,
        hpBonus: 440,
        speedBonus: 0.09,
        priceGem: 350,
        image: '/assets/images/items/boots/boots_grozovogo_vestnika.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Искрятся молниями, увеличивая скорость перемещения.',
    },

    boots_rune: {
        id: 'boots_rune',
        name: 'Эфирные Следоходы',
        requiredLevel: 34,
        rarity: 'EPIC',
        defenseBonus: 50,
        hpBonus: 550,
        speedBonus: 0.14,
        priceGold: 52000,
        image: '/assets/images/items/boots/boots_3.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Магические руны делают походку легкой, как сам эфир.',
    },

    boots_nekromanta: {
        id: 'boots_nekromanta',
        name: 'Сапоги Некроманта',
        requiredLevel: 40,
        rarity: 'EPIC',
        defenseBonus: 61,
        hpBonus: 671,
        speedBonus: 0.06,
        priceGem: 700,
        image: '/assets/images/items/boots/boots_nekromanta.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Овеяны замогильной прохладой, замедляют старение плоти.',
    },

    botforty_pustotnogo_ohotnika: {
        id: 'botforty_pustotnogo_ohotnika',
        name: 'Ботфорты Пустотного Охотника',
        requiredLevel: 46,
        rarity: 'EPIC',
        defenseBonus: 72,
        hpBonus: 792,
        speedBonus: 0.12,
        priceGold: 70000,
        image: '/assets/images/items/boots/botforty_pustotnogo_ohotnika.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Сшиты из кожи созданий Бездны, бесшумные и прочные.',
    },

    sabatony_drakoney_cheshui: {
        id: 'sabatony_drakoney_cheshui',
        name: 'Сабатоны Драконьей Чешуи',
        requiredLevel: 47,
        rarity: 'LEGENDARY',
        defenseBonus: 74,
        hpBonus: 814,
        speedBonus: 0.08,
        priceGem: 900,
        image: '/assets/images/items/boots/sabatony_drakoney_cheshui.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Кованая обувь, покрытая огнеупорной чешуей красного дракона.',
    },

    boots_paladin: {
        id: 'boots_paladin',
        name: 'Сапоги Солнечного Императора',
        requiredLevel: 63,
        rarity: 'LEGENDARY',
        defenseBonus: 105,
        hpBonus: 1155,
        speedBonus: 0.08,
        priceGold: 95000,
        image: '/assets/images/items/boots/boots_7.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Величественная броня, сияющая светом тысячи солнц.',
    },

    postup_zvezdnogo_skitalca: {
        id: 'postup_zvezdnogo_skitalca',
        name: 'Поступь Звёздного Скитальца',
        requiredLevel: 64,
        rarity: 'MYTHIC',
        defenseBonus: 107,
        hpBonus: 1177,
        speedBonus: 0.18,
        priceGem: 1200,
        image: '/assets/images/items/boots/postup_zvezdnogo_skitalca.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Космическая пыль оседает за каждым шагом владельца этих сапог.',
    },

    boots_bone: {
        id: 'boots_bone',
        name: 'Поступь Повелителя Мертвых',
        requiredLevel: 80,
        rarity: 'MYTHIC',
        defenseBonus: 140,
        hpBonus: 1540,
        speedBonus: 0.2,
        priceGold: 115000,
        image: '/assets/images/items/boots/boots_4.webp',
        mainTab: 'ARSENAL',
        subTab: 'BOOTS',
        desc: 'Каждый шаг пробуждает тени прошлого.',
    },
};
