import { IEquipmentStats } from './types';

export const consumables: Record<string, IEquipmentStats> = {
    season_chest: {
        id: 'season_chest',
        name: 'Сундук Сезона',
        priceGem: 250,
        image: '/assets/images/ui/icons/season_chest.webp',
        rarity: 'LEGENDARY',
        mainTab: 'ALCHEMY',
        subTab: 'CHESTS',
        desc: 'Легендарный сундук за достижения в сезоне. Содержит один случайный предмет экипировки из магазина.',
    },
    hp_potion_1: {
        id: 'hp_potion_1',
        name: 'Малое Зелье Жизни',
        priceGold: 200,
        image: '/assets/images/items/potions/hp_small.webp',
        rarity: 'COMMON',
        mainTab: 'ALCHEMY',
        subTab: 'POTIONS',
        hpBonus: 100,
        desc: 'Восстанавливает небольшое количество здоровья.',
    },
    hp_potion_2: {
        id: 'hp_potion_2',
        name: 'Среднее Зелье Жизни',
        priceGold: 800,
        image: '/assets/images/items/potions/defense.webp',
        rarity: 'RARE',
        mainTab: 'ALCHEMY',
        subTab: 'POTIONS',
        hpBonus: 300,
        desc: 'Эффективно залечивает раны в разгаре боя.',
    },
    hp_potion_3: {
        id: 'hp_potion_3',
        name: 'Великое Зелье Жизни',
        priceGem: 50,
        image: '/assets/images/items/potions/strength.webp',
        rarity: 'EPIC',
        mainTab: 'ALCHEMY',
        subTab: 'POTIONS',
        hpBonus: 1000,
        desc: 'Мгновенно восстанавливает жизненные силы.',
    },
    mana_potion_1: {
        id: 'mana_potion_1',
        name: 'Зелье Маны',
        priceGold: 300,
        image: '/assets/images/items/potions/speed.webp',
        rarity: 'COMMON',
        mainTab: 'ALCHEMY',
        subTab: 'POTIONS',
        desc: 'Восполняет магическую энергию.',
    },
    // --- БАНК / РЕСУРСЫ ---
    gem_pack_1: {
        id: 'gem_pack_1',
        name: 'Горсть Алмазов',
        priceStars: 20,
        image: '/assets/images/shop/bank_almaz_small.webp',
        rarity: 'RARE',
        mainTab: 'BANK',
        subTab: 'GEMS',
        desc: 'Набор из 100 алмазов.',
        amount: 100,
    },
    gem_pack_2: {
        id: 'gem_pack_2',
        name: 'Сундук Алмазов',
        priceStars: 100,
        image: '/assets/images/shop/bank_almaz_medium.webp',
        rarity: 'EPIC',
        mainTab: 'BANK',
        subTab: 'GEMS',
        desc: 'Набор из 600 алмазов.',
        amount: 600,
    },
    gem_pack_3: {
        id: 'gem_pack_3',
        name: 'Сокровищница Алмазов',
        priceStars: 500,
        image: '/assets/images/shop/bank_almaz_large.webp',
        rarity: 'LEGENDARY',
        mainTab: 'BANK',
        subTab: 'GEMS',
        desc: 'Набор из 3500 алмазов.',
        amount: 3500,
    },
    gold_pack_1: {
        id: 'gold_pack_1',
        name: 'Кошелек Золота',
        priceGem: 100,
        image: '/assets/images/shop/bank_gold_small.webp',
        rarity: 'RARE',
        mainTab: 'BANK',
        subTab: 'GOLD',
        desc: 'Набор из 10 000 золота.',
        amount: 10000,
    },
    gold_pack_2: {
        id: 'gold_pack_2',
        name: 'Сундук Золота',
        priceGem: 500,
        image: '/assets/images/shop/bank_gold_medium.webp',
        rarity: 'EPIC',
        mainTab: 'BANK',
        subTab: 'GOLD',
        desc: 'Набор из 60 000 золота.',
        amount: 60000,
    },
    gold_pack_3: {
        id: 'gold_pack_3',
        name: 'Сокровищница Золота',
        priceGem: 2000,
        image: '/assets/images/shop/bank_gold_large.webp',
        rarity: 'LEGENDARY',
        mainTab: 'BANK',
        subTab: 'GOLD',
        desc: 'Набор из 300 000 золота.',
        amount: 300000,
    },
    ad_energy: {
        id: 'ad_energy',
        name: 'Энергия за рекламу',
        isAd: true,
        image: '/assets/images/shop/bank_energy_1.webp',
        rarity: 'COMMON',
        mainTab: 'BANK',
        subTab: 'ENERGY',
        desc: 'Смотрите рекламу, чтобы получить 20 энергии.',
        amount: 20,
    },
    ad_gold: {
        id: 'ad_gold',
        name: 'Золото за рекламу',
        isAd: true,
        image: '/assets/images/shop/bank_gold_small.webp',
        rarity: 'COMMON',
        mainTab: 'BANK',
        subTab: 'GOLD',
        desc: 'Смотрите рекламу, чтобы получить 2 500 золота.',
        amount: 2500,
    },
    ad_gems: {
        id: 'ad_gems',
        name: 'Алмазы за рекламу',
        isAd: true,
        image: '/assets/images/shop/bank_almaz_small.webp',
        rarity: 'COMMON',
        mainTab: 'BANK',
        subTab: 'GEMS',
        desc: 'Смотрите рекламу, чтобы получить 20 алмазов.',
        amount: 20,
    },
    '40': {
        id: '40',
        name: 'Малый эликсир',
        priceGem: 50,
        image: '/assets/images/shop/bank_energy_1.webp',
        rarity: 'COMMON',
        mainTab: 'BANK',
        subTab: 'ENERGY',
        desc: '50 энергии.',
        amount: 50,
    },
    '41': {
        id: '41',
        name: 'Средний эликсир',
        priceGem: 200,
        image: '/assets/images/shop/bank_energy_2.webp',
        rarity: 'RARE',
        mainTab: 'BANK',
        subTab: 'ENERGY',
        desc: '250 энергии.',
        amount: 250,
    },
    '42': {
        id: '42',
        name: 'Великий эликсир',
        priceGem: 500,
        image: '/assets/images/shop/bank_energy_3.webp',
        rarity: 'EPIC',
        mainTab: 'BANK',
        subTab: 'ENERGY',
        desc: '750 энергии.',
        amount: 750,
    },
    coal: {
        id: 'coal',
        name: 'Уголь',
        image: '/assets/images/resources/coal.webp',
        rarity: 'COMMON',
        mainTab: 'ALCHEMY',
        subTab: 'RESOURCES',
        desc: 'Простой уголь для растопки горнила кузницы.',
    },
    steel_bar: {
        id: 'steel_bar',
        name: 'Стальной слиток',
        image: '/assets/images/resources/steel_bar.webp',
        rarity: 'RARE',
        mainTab: 'ALCHEMY',
        subTab: 'RESOURCES',
        desc: 'Прочный стальной слиток для ковки брони и оружия.',
    },
    runic_shard: {
        id: 'runic_shard',
        name: 'Рунический осколок',
        image: '/assets/images/resources/runic_shard.webp',
        rarity: 'EPIC',
        mainTab: 'ALCHEMY',
        subTab: 'RESOURCES',
        desc: 'Магический осколок руны, концентрирующий чистую энергию.',
    },
    ancient_compass: {
        id: 'ancient_compass',
        name: 'Древний компас',
        image: '/assets/images/resources/ancient_compass.webp',
        rarity: 'RARE',
        mainTab: 'ALCHEMY',
        subTab: 'RESOURCES',
        desc: 'Древний компас, указывающий путь к скрытым сокровищам.',
    },
    astral_crystal: {
        id: 'astral_crystal',
        name: 'Астральный кристалл',
        image: '/assets/images/resources/astral_crystal.webp',
        rarity: 'RARE',
        mainTab: 'ALCHEMY',
        subTab: 'RESOURCES',
        desc: 'Кристалл, вобравший в себя мерцание далеких звезд.',
    },
    void_sphere: {
        id: 'void_sphere',
        name: 'Сфера бездны',
        image: '/assets/images/resources/void_sphere.webp',
        rarity: 'EPIC',
        mainTab: 'ALCHEMY',
        subTab: 'RESOURCES',
        desc: 'Сфера из чистой пустоты, притягивающая к себе окружающую материю.',
    },
    golden_sprout: {
        id: 'golden_sprout',
        name: 'Золотой росток',
        image: '/assets/images/resources/golden_sprout.webp',
        rarity: 'EPIC',
        mainTab: 'ALCHEMY',
        subTab: 'RESOURCES',
        desc: 'Золотой росток священного дерева, обладающий невероятной жизненной силой.',
    },
    dragon_scale: {
        id: 'dragon_scale',
        name: 'Чешуя дракона',
        image: '/assets/images/resources/dragon_scale.webp',
        rarity: 'LEGENDARY',
        mainTab: 'ALCHEMY',
        subTab: 'RESOURCES',
        desc: 'Невероятно прочная чешуя древнего дракона, способная выдержать колоссальный урон.',
    },
    lava_heart: {
        id: 'lava_heart',
        name: 'Сердце лавы',
        image: '/assets/images/resources/lava_heart.webp',
        rarity: 'LEGENDARY',
        mainTab: 'ALCHEMY',
        subTab: 'RESOURCES',
        desc: 'Пульсирующее ядро огненного голема, источающее обжигающее тепло.',
    },
    protection_stone: {
        id: 'protection_stone',
        name: 'Камень Защиты',
        priceGem: 80,
        image: '/assets/images/resources/protection_stone.webp',
        rarity: 'EPIC',
        mainTab: 'ALCHEMY',
        subTab: 'POTIONS',
        desc: 'Предотвращает понижение уровня улучшения предмета при неудаче в кузнице.',
    },
    exp_potion_small: {
        id: 'exp_potion_small',
        name: 'Малое Зелье Опыта',
        desc: 'Даёт персонажу 2 000 единиц опыта',
        rarity: 'COMMON',
        expReward: 2000,
        priceGem: 50,
        image: '/assets/images/items/potions/exp_small.webp',
        requiredLevel: 1,
        mainTab: 'ALCHEMY',
        subTab: 'POTIONS',
    },
    exp_potion_medium: {
        id: 'exp_potion_medium',
        name: 'Среднее Зелье Опыта',
        desc: 'Даёт персонажу 10 000 единиц опыта',
        rarity: 'RARE',
        expReward: 10000,
        priceGem: 200,
        image: '/assets/images/items/potions/exp_medium.webp',
        requiredLevel: 1,
        mainTab: 'ALCHEMY',
        subTab: 'POTIONS',
    },
    exp_potion_large: {
        id: 'exp_potion_large',
        name: 'Большое Зелье Опыта',
        desc: 'Даёт персонажу 50 000 единиц опыта',
        rarity: 'EPIC',
        expReward: 50000,
        priceGem: 800,
        image: '/assets/images/items/potions/exp_large.webp',
        requiredLevel: 1,
        mainTab: 'ALCHEMY',
        subTab: 'POTIONS',
    },
};
