import { IEquipmentStats, ItemRarity } from './types';

export const helmets: Record<string, IEquipmentStats> = {
    h1: {
        id: 'h1',
        name: 'Венец Аметистового Властелина',
        rarity: ItemRarity.EPIC,
        priceGem: 400,
        requiredLevel: 28,
        defenseBonus: 51,
        hpBonus: 509,
        image: '/assets/images/items/helms/helm_crown.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Древний аметистовый артефакт, излучающий ауру власти.',
    },
    h2: {
        id: 'h2',
        name: 'Шлем Проклятого Самурая',
        rarity: ItemRarity.RARE,
        priceGold: 8000,
        requiredLevel: 14,
        defenseBonus: 25,
        hpBonus: 250,
        image: '/assets/images/items/helms/helm_ext_2.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Освященный металл, благословленный жрецами света.',
    },
    h3: {
        id: 'h3',
        name: 'Золотой Лик Фараона',
        rarity: ItemRarity.EPIC,
        priceGem: 550,
        requiredLevel: 32,
        defenseBonus: 55,
        hpBonus: 547,
        image: '/assets/images/items/helms/helm_ext_1.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Тяжелый шлем элитных стражей забытой империи.',
    },
    h4: {
        id: 'h4',
        name: 'Золотой Оракул',
        rarity: 'MYTHIC',
        priceGem: 5500,
        requiredLevel: 70,
        defenseBonus: 204,
        hpBonus: 2040,
        image: '/assets/images/items/helms/bone_mask.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Дыхание бездны всё еще ощущается внутри этого шлема.',
    },
    h_dark: {
        id: 'h_dark',
        name: 'Шлем Теневого Дракона',
        rarity: 'MYTHIC',
        priceGem: 6500,
        requiredLevel: 75,
        defenseBonus: 214,
        hpBonus: 2140,
        image: '/assets/images/items/helms/helm_ext_8.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Тьма внутри него шепчет забытые заклинания.',
    },
    h_forest: {
        id: 'h_forest',
        name: 'Капюшон Лесного Странника',
        rarity: 'RARE',
        priceGold: 5000,
        requiredLevel: 10,
        defenseBonus: 22,
        hpBonus: 224,
        image: '/assets/images/items/helms/forest_hood.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Сплетен из веток священного древа.',
    },
    h5: {
        id: 'h5',
        name: 'Шлем Небесного Стража',
        rarity: 'EPIC',
        priceGem: 700,
        requiredLevel: 35,
        defenseBonus: 58,
        hpBonus: 576,
        image: '/assets/images/items/helms/helm_ext_5.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Притягивает молнии, которые питают владельца силой.',
    },
    h6: {
        id: 'h6',
        name: 'Шлем Серебряного Валькирия',
        rarity: 'RARE',
        priceGold: 15000,
        requiredLevel: 16,
        defenseBonus: 26,
        hpBonus: 262,
        image: '/assets/images/items/helms/helm_ext_6.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Древняя маска, хранящая кодекс чести.',
    },
    h7: {
        id: 'h7',
        name: 'Капюшон Ночного Охотника',
        rarity: 'EPIC',
        priceGem: 850,
        requiredLevel: 38,
        defenseBonus: 60,
        hpBonus: 605,
        image: '/assets/images/items/helms/helm_ext_7.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Замораживает взгляды врагов.',
    },
    h9: {
        id: 'h9',
        name: 'Капюшон Скрытности',
        rarity: 'RARE',
        priceGold: 10000,
        requiredLevel: 12,
        defenseBonus: 24,
        hpBonus: 237,
        image: '/assets/images/items/helms/helm_ext_9.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Позволяет слиться с тенями.',
    },
    h10: {
        id: 'h10',
        name: 'Шлем Несокрушимого Титана',
        rarity: 'EPIC',
        priceGem: 950,
        requiredLevel: 40,
        defenseBonus: 62,
        hpBonus: 624,
        image: '/assets/images/items/helms/helm_ext_10.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Тяжелая броня из истинного мифрила.',
    },
    h11: {
        id: 'h11',
        name: 'Маска Кровавого Они',
        rarity: 'RARE',
        priceGold: 20000,
        requiredLevel: 18,
        defenseBonus: 28,
        hpBonus: 275,
        image: '/assets/images/items/helms/helm_ext_11.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Линзы позволяют видеть сквозь туман войны.',
    },
    h12: {
        id: 'h12',
        name: 'Лик Повелителя Мертвых',
        rarity: 'LEGENDARY',
        priceGem: 2000,
        requiredLevel: 52,
        defenseBonus: 115,
        hpBonus: 1149,
        image: '/assets/images/items/helms/helm_ext_12.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Мощи древнего зверя всё еще живет в этой кости.',
    },
    h14: {
        id: 'h14',
        name: 'Шлем Солнечного Рыцаря',
        rarity: 'EPIC',
        priceGem: 1100,
        requiredLevel: 45,
        defenseBonus: 67,
        hpBonus: 672,
        image: '/assets/images/items/helms/helm_ext_14.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Сияет так ярко, что враги не могут прицелиться.',
    },
    h15: {
        id: 'h15',
        name: 'Лик Огненного Феникса',
        rarity: 'MYTHIC',
        priceGem: 8000,
        requiredLevel: 80,
        defenseBonus: 224,
        hpBonus: 2240,
        image: '/assets/images/items/helms/helm_fire.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Каждый вдох в этом шлеме наполняет кровь огнем.',
    },
    h16: {
        id: 'h16',
        name: 'Венец Звездного Императора',
        rarity: 'LEGENDARY',
        priceGem: 3200,
        requiredLevel: 58,
        defenseBonus: 124,
        hpBonus: 1235,
        image: '/assets/images/items/helms/helm_lion.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Управляй силой созвездий.',
    },
    bandana: {
        id: 'bandana',
        name: 'Повязка Скитальца',
        priceGold: 80,
        requiredLevel: 1,
        image: '/assets/images/items/helms/bandana.webp',
        rarity: 'COMMON',
        defenseBonus: 8,
        hpBonus: 84,
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Старая повязка, защищающая от пыли дорог.',
        textureKey: 'helm_bandana',
    },
    iron_helm: {
        id: 'iron_helm',
        name: 'Шлем Королевской Гвардии',
        image: '/assets/images/items/helms/iron_helm.webp',
        rarity: 'RARE',
        priceGold: 25000,
        requiredLevel: 20,
        defenseBonus: 29,
        hpBonus: 288,
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Надежный стальной шлем.',
        textureKey: 'helm_iron',
    },
    starter_helm: {
        id: 'starter_helm',
        name: 'Кожаный Шлем',
        priceGold: 150,
        requiredLevel: 1,
        image: '/assets/images/items/helms/starter_helm.webp',
        rarity: 'COMMON',
        defenseBonus: 8,
        hpBonus: 84,
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        textureKey: 'helm_leather',
        desc: 'Простая защита головы из потертой кожи.',
    },
    helm_skull: {
        id: 'helm_skull',
        name: 'Костяной Шлем Погибели',
        rarity: 'RARE',
        priceGold: 22000,
        requiredLevel: 19,
        defenseBonus: 28,
        hpBonus: 282,
        image: '/assets/images/items/helms/helm_skull.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Пустые глазницы этого шлема вселяют ужас.',
    },
    helm_ranger: {
        id: 'helm_ranger',
        name: 'Кожаный Капюшон Рейнджера',
        rarity: 'RARE',
        priceGold: 2000,
        requiredLevel: 10,
        defenseBonus: 22,
        hpBonus: 224,
        image: '/assets/images/items/helms/forest_hood.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Легкий капюшон, помогающий замаскироваться среди лесной листвы.',
    },
    helm_steampunk: {
        id: 'helm_steampunk',
        name: 'Визор Парового Инженера',
        rarity: 'EPIC',
        priceGem: 300,
        requiredLevel: 25,
        defenseBonus: 48,
        hpBonus: 480,
        image: '/assets/images/items/helms/helm_steampunk.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Высокотехнологичный прибор для анализа поля боя.',
    },
};
