import { IEquipmentStats } from './types';

export const helmets: Record<string, IEquipmentStats> = {
    bandana: {
        id: 'bandana',
        name: 'Повязка Скитальца',
        requiredLevel: 1,
        rarity: 'COMMON',
        defenseBonus: 8,
        hpBonus: 80,
        priceGold: 1800,
        image: '/assets/images/items/helms/bandana.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Старая повязка, защищающая от пыли дорог.',
        textureKey: 'helm_bandana',
    },

    starter_helm: {
        id: 'starter_helm',
        name: 'Кожаный Шлем',
        requiredLevel: 3,
        rarity: 'COMMON',
        defenseBonus: 10,
        hpBonus: 100,
        priceGem: 18,
        image: '/assets/images/items/helms/starter_helm.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Простая защита головы из потертой кожи.',
        textureKey: 'helm_leather',
    },

    h_forest: {
        id: 'h_forest',
        name: 'Капюшон Лесного Странника',
        requiredLevel: 11,
        rarity: 'RARE',
        defenseBonus: 24,
        hpBonus: 240,
        priceGold: 11000,
        image: '/assets/images/items/helms/forest_hood.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Сплетен из веток священного древа.',
    },

    h9: {
        id: 'h9',
        name: 'Капюшон Скрытности',
        requiredLevel: 13,
        rarity: 'RARE',
        defenseBonus: 28,
        hpBonus: 280,
        priceGem: 40,
        image: '/assets/images/items/helms/helm_ext_9.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Позволяет слиться с тенями.',
    },

    helm_ranger: {
        id: 'helm_ranger',
        name: 'Кожаный Капюшон Рейнджера',
        requiredLevel: 16,
        rarity: 'RARE',
        defenseBonus: 35,
        hpBonus: 350,
        priceGold: 20000,
        image: '/assets/images/items/helms/helm_ext_3.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Легкий капюшон, помогающий замаскироваться среди лесной листвы.',
    },

    h6: {
        id: 'h6',
        name: 'Шлем Серебряного Валькирия',
        requiredLevel: 18,
        rarity: 'RARE',
        defenseBonus: 40,
        hpBonus: 400,
        priceGem: 110,
        image: '/assets/images/items/helms/helm_ext_6.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Древняя маска, хранящая кодекс чести.',
    },

    h11: {
        id: 'h11',
        name: 'Маска Кровавого Они',
        requiredLevel: 20,
        rarity: 'RARE',
        defenseBonus: 44,
        hpBonus: 440,
        priceGold: 30000,
        image: '/assets/images/items/helms/helm_ext_11.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Линзы позволяют видеть сквозь туман войны.',
    },

    h2: {
        id: 'h2',
        name: 'Шлем Проклятого Самурая',
        requiredLevel: 22,
        rarity: 'RARE',
        defenseBonus: 49,
        hpBonus: 490,
        priceGem: 250,
        image: '/assets/images/items/helms/helm_ext_2.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Освященный металл, благословленный жрецами света.',
    },

    helm_skull: {
        id: 'helm_skull',
        name: 'Костяной Шлем Погибели',
        requiredLevel: 25,
        rarity: 'RARE',
        defenseBonus: 57,
        hpBonus: 570,
        priceGold: 42000,
        image: '/assets/images/items/helms/helm_skull.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Пустые глазницы этого шлема вселяют ужас.',
    },

    iron_helm: {
        id: 'iron_helm',
        name: 'Шлем Королевской Гвардии',
        requiredLevel: 27,
        rarity: 'RARE',
        defenseBonus: 62,
        hpBonus: 620,
        priceGem: 430,
        image: '/assets/images/items/helms/iron_helm.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Надежный стальной шлем.',
        textureKey: 'helm_iron',
    },

    h3: {
        id: 'h3',
        name: 'Золотой Лик Фараона',
        requiredLevel: 28,
        rarity: 'EPIC',
        defenseBonus: 64,
        hpBonus: 640,
        priceGold: 50000,
        image: '/assets/images/items/helms/helm_ext_1.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Тяжелый шлем элитных стражей забытой империи.',
    },

    h7: {
        id: 'h7',
        name: 'Капюшон Ночного Охотника',
        requiredLevel: 32,
        rarity: 'EPIC',
        defenseBonus: 75,
        hpBonus: 750,
        priceGem: 650,
        image: '/assets/images/items/helms/helm_ext_7.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Замораживает взгляды врагов.',
    },

    helm_steampunk: {
        id: 'helm_steampunk',
        name: 'Визор Парового Инженера',
        requiredLevel: 35,
        rarity: 'EPIC',
        defenseBonus: 83,
        hpBonus: 830,
        priceGold: 70000,
        image: '/assets/images/items/helms/helm_steampunk.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Высокотехнологичный прибор для анализа поля боя.',
    },

    h1: {
        id: 'h1',
        name: 'Венец Аметистового Властелина',
        requiredLevel: 39,
        rarity: 'EPIC',
        defenseBonus: 95,
        hpBonus: 950,
        priceGem: 820,
        image: '/assets/images/items/helms/helm_crown.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Древний аметистовый артефакт, излучающий ауру власти.',
    },

    h10: {
        id: 'h10',
        name: 'Шлем Несокрушимого Титана',
        requiredLevel: 42,
        rarity: 'EPIC',
        defenseBonus: 103,
        hpBonus: 1030,
        priceGold: 85000,
        image: '/assets/images/items/helms/helm_ext_10.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Тяжелая броня из истинного мифрила.',
    },

    h5: {
        id: 'h5',
        name: 'Шлем Небесного Стража',
        requiredLevel: 46,
        rarity: 'EPIC',
        defenseBonus: 115,
        hpBonus: 1150,
        priceGem: 950,
        image: '/assets/images/items/helms/helm_ext_5.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Притягивает молнии, которые питают владельца силой.',
    },

    h12: {
        id: 'h12',
        name: 'Лик Повелителя Мертвых',
        requiredLevel: 47,
        rarity: 'LEGENDARY',
        defenseBonus: 118,
        hpBonus: 1180,
        priceGold: 100000,
        image: '/assets/images/items/helms/helm_ext_12.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Мощи древнего зверя всё еще живет в этой кости.',
    },

    h4: {
        id: 'h4',
        name: 'Золотой Оракул',
        requiredLevel: 52,
        rarity: 'LEGENDARY',
        defenseBonus: 133,
        hpBonus: 1330,
        priceGem: 1100,
        image: '/assets/images/items/helms/bone_mask.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Дыхание бездны всё еще ощущается внутри этого шлема.',
    },

    h14: {
        id: 'h14',
        name: 'Шлем Солнечного Рыцаря',
        requiredLevel: 58,
        rarity: 'LEGENDARY',
        defenseBonus: 152,
        hpBonus: 1520,
        priceGold: 110000,
        image: '/assets/images/items/helms/helm_ext_14.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Сияет так ярко, что враги не могут прицелиться.',
    },

    h16: {
        id: 'h16',
        name: 'Венец Звездного Императора',
        requiredLevel: 63,
        rarity: 'LEGENDARY',
        defenseBonus: 168,
        hpBonus: 1680,
        priceGem: 1400,
        image: '/assets/images/items/helms/helm_lion.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Управляй силой созвездий.',
    },

    h_dark: {
        id: 'h_dark',
        name: 'Шлем Теневого Дракона',
        requiredLevel: 64,
        rarity: 'MYTHIC',
        defenseBonus: 171,
        hpBonus: 1710,
        priceGold: 150000,
        image: '/assets/images/items/helms/helm_ext_8.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Тьма внутри него шепчет забытые заклинания.',
    },

    h15: {
        id: 'h15',
        name: 'Лик Огненного Феникса',
        requiredLevel: 80,
        rarity: 'MYTHIC',
        defenseBonus: 224,
        hpBonus: 2240,
        priceGem: 1700,
        image: '/assets/images/items/helms/helm_fire.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Каждый вдох в этом шлеме наполняет кровь огнем.',
    },
};
