import { IEquipmentStats, ItemRarity } from './types';

export const helmets: Record<string, IEquipmentStats> = {
    h1: {
        id: 'h1',
        name: 'Венец Аметистового Властелина',
        defenseBonus: 80,
        hpBonus: 800,
        rarity: ItemRarity.EPIC,
        priceGem: 400,
        requiredLevel: 28,
        image: '/assets/images/items/helms/helm_crown.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Древний аметистовый артефакт, излучающий ауру власти.',
    },
    h2: {
        id: 'h2',
        name: 'Шлем Проклятого Самурая',
        defenseBonus: 45,
        hpBonus: 450,
        rarity: ItemRarity.RARE,
        priceGold: 8000,
        requiredLevel: 14,
        image: '/assets/images/items/helms/helm_ext_2.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Освященный металл, благословленный жрецами света.',
    },
    h3: {
        id: 'h3',
        name: 'Золотой Лик Фараона',
        defenseBonus: 100,
        hpBonus: 1000,
        rarity: ItemRarity.EPIC,
        priceGem: 550,
        requiredLevel: 32,
        image: '/assets/images/items/helms/helm_ext_1.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Тяжелый шлем элитных стражей забытой империи.',
    },
    h4: {
        id: 'h4',
        name: 'Золотой Оракул',
        defenseBonus: 500,
        hpBonus: 5000,
        rarity: 'MYTHIC',
        priceGem: 5500,
        requiredLevel: 70,
        image: '/assets/images/items/helms/bone_mask.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Дыхание бездны всё еще ощущается внутри этого шлема.',
    },
    h_dark: {
        id: 'h_dark',
        name: 'Шлем Теневого Дракона',
        defenseBonus: 650,
        hpBonus: 6500,
        rarity: 'MYTHIC',
        priceGem: 6500,
        requiredLevel: 75,
        image: '/assets/images/items/helms/helm_ext_8.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Тьма внутри него шепчет забытые заклинания.',
    },
    h_forest: {
        id: 'h_forest',
        name: 'Капюшон Лесного Странника',
        defenseBonus: 35,
        hpBonus: 350,
        rarity: 'RARE',
        priceGold: 5000,
        requiredLevel: 10,
        image: '/assets/images/items/helms/forest_hood.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Сплетен из веток священного древа.',
    },
    h5: {
        id: 'h5',
        name: 'Шлем Небесного Стража',
        defenseBonus: 120,
        hpBonus: 1200,
        rarity: 'EPIC',
        priceGem: 700,
        requiredLevel: 35,
        image: '/assets/images/items/helms/helm_ext_5.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Притягивает молнии, которые питают владельца силой.',
    },
    h6: {
        id: 'h6',
        name: 'Шлем Серебряного Валькирия',
        defenseBonus: 55,
        hpBonus: 550,
        rarity: 'RARE',
        priceGold: 15000,
        requiredLevel: 16,
        image: '/assets/images/items/helms/helm_ext_6.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Древняя маска, хранящая кодекс чести.',
    },
    h7: {
        id: 'h7',
        name: 'Капюшон Ночного Охотника',
        defenseBonus: 140,
        hpBonus: 1400,
        rarity: 'EPIC',
        priceGem: 850,
        requiredLevel: 38,
        image: '/assets/images/items/helms/helm_ext_7.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Замораживает взгляды врагов.',
    },
    h9: {
        id: 'h9',
        name: 'Капюшон Скрытности',
        defenseBonus: 40,
        hpBonus: 400,
        rarity: 'RARE',
        priceGold: 10000,
        requiredLevel: 12,
        image: '/assets/images/items/helms/helm_ext_9.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Позволяет слиться с тенями.',
    },
    h10: {
        id: 'h10',
        name: 'Шлем Несокрушимого Титана',
        defenseBonus: 150,
        hpBonus: 1500,
        rarity: 'EPIC',
        priceGem: 950,
        requiredLevel: 40,
        image: '/assets/images/items/helms/helm_ext_10.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Тяжелая броня из истинного мифрила.',
    },
    h11: {
        id: 'h11',
        name: 'Маска Кровавого Они',
        defenseBonus: 65,
        hpBonus: 650,
        rarity: 'RARE',
        priceGold: 20000,
        requiredLevel: 18,
        image: '/assets/images/items/helms/helm_ext_11.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Линзы позволяют видеть сквозь туман войны.',
    },
    h12: {
        id: 'h12',
        name: 'Лик Повелителя Мертвых',
        defenseBonus: 280,
        hpBonus: 2800,
        rarity: 'LEGENDARY',
        priceGem: 2000,
        requiredLevel: 52,
        image: '/assets/images/items/helms/helm_ext_12.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Мощи древнего зверя всё еще живет в этой кости.',
    },
    h14: {
        id: 'h14',
        name: 'Шлем Солнечного Рыцаря',
        defenseBonus: 200,
        hpBonus: 2000,
        rarity: 'EPIC',
        priceGem: 1100,
        requiredLevel: 45,
        image: '/assets/images/items/helms/helm_ext_14.png',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Сияет так ярко, что враги не могут прицелиться.',
    },
    h15: {
        id: 'h15',
        name: 'Лик Огненного Феникса',
        defenseBonus: 800,
        hpBonus: 8000,
        rarity: 'MYTHIC',
        priceGem: 8000,
        requiredLevel: 80,
        image: '/assets/images/items/helms/helm_fire.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Каждый вдох в этом шлеме наполняет кровь огнем.',
    },
    h16: {
        id: 'h16',
        name: 'Венец Звездного Императора',
        defenseBonus: 380,
        hpBonus: 3800,
        rarity: 'LEGENDARY',
        priceGem: 3200,
        requiredLevel: 58,
        image: '/assets/images/items/helms/helm_lion.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Управляй силой созвездий.',
    },
    bandana: {
        id: 'bandana',
        name: 'Повязка Скитальца',
        defenseBonus: 3,
        hpBonus: 30,
        priceGold: 80,
        requiredLevel: 1,
        image: '/assets/images/items/helms/bandana.webp',
        rarity: 'COMMON',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Старая повязка, защищающая от пыли дорог.',
        textureKey: 'helm_bandana',
    },
    iron_helm: {
        id: 'iron_helm',
        name: 'Шлем Королевской Гвардии',
        defenseBonus: 75,
        hpBonus: 750,
        image: '/assets/images/items/helms/iron_helm.webp',
        rarity: 'RARE',
        priceGold: 25000,
        requiredLevel: 20,
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Надежный стальной шлем.',
        textureKey: 'helm_iron',
    },
    starter_helm: {
        id: 'starter_helm',
        name: 'Кожаный Шлем',
        priceGold: 150,
        requiredLevel: 1,
        image: '/assets/images/items/helms/starter_helm.webp',
        rarity: 'COMMON',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        textureKey: 'helm_leather',
        defenseBonus: 5,
        hpBonus: 50,
        desc: 'Простая защита головы из потертой кожи.',
    },
    helm_skull: {
        id: 'helm_skull',
        name: 'Костяной Шлем Погибели',
        defenseBonus: 80,
        hpBonus: 800,
        rarity: 'RARE',
        priceGold: 22000,
        requiredLevel: 19,
        image: '/assets/images/items/helms/helm_skull.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Пустые глазницы этого шлема вселяют ужас.',
    },
    helm_ranger: {
        id: 'helm_ranger',
        name: 'Кожаный Капюшон Рейнджера',
        defenseBonus: 10,
        hpBonus: 100,
        rarity: 'RARE',
        priceGold: 2000,
        requiredLevel: 10,
        image: '/assets/images/items/helms/forest_hood.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Легкий капюшон, помогающий замаскироваться среди лесной листвы.',
    },
    helm_steampunk: {
        id: 'helm_steampunk',
        name: 'Визор Парового Инженера',
        defenseBonus: 65,
        hpBonus: 650,
        rarity: 'EPIC',
        priceGem: 300,
        requiredLevel: 25,
        image: '/assets/images/items/helms/helm_steampunk.webp',
        mainTab: 'ARSENAL',
        subTab: 'HELMETS',
        desc: 'Высокотехнологичный прибор для анализа поля боя.',
    },
};
