import { IEquipmentStats } from './types';

export const pants: Record<string, IEquipmentStats> = {
    // COMMON - Ткань и кожа (самые дешевые и слабые)
    pants_mythic: {
        id: 'pants_mythic',
        name: 'Штаны Скитальца',
        requiredLevel: 3,
        rarity: 'COMMON',
        hpBonus: 98,
        speedBonus: 0.01,
        priceGold: 200,
        image: '/assets/images/items/pants/pants_mythic.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Простая кожаная одежда, не стесняющая движений.',
    },
    pants_void: {
        id: 'pants_void',
        name: 'Рваные Обноски',
        requiredLevel: 1,
        rarity: 'COMMON',
        hpBonus: 89,
        speedBonus: 0.02,
        priceGold: 350,
        image: '/assets/images/items/pants/pants_void.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Старые штаны, которые давно пора пустить на ветошь.',
    },
    pants_storm: {
        id: 'pants_storm',
        name: 'Кожаные Брюки',
        requiredLevel: 10,
        rarity: 'COMMON',
        hpBonus: 128,
        speedBonus: 0.02,
        priceGold: 550,
        image: '/assets/images/items/pants/pants_storm.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Обычные брюки из грубой кожи.',
    },
    pants_spiked: {
        id: 'pants_spiked',
        name: 'Брюки Охотника',
        requiredLevel: 5,
        rarity: 'COMMON',
        hpBonus: 106,
        speedBonus: 0.03,
        priceGold: 800,
        image: '/assets/images/items/pants/pants_spiked.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Практичная одежда для вылазок в лес.',
    },

    // RARE - Укрепленная кожа и простое железо
    pants_mercenary: {
        id: 'pants_mercenary',
        name: 'Поножи Наемника',
        requiredLevel: 11,
        rarity: 'RARE',
        hpBonus: 245,
        priceGold: 5000,
        image: '/assets/images/items/pants/pants_mercenary.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        speedBonus: 0.03,
        desc: 'Укрепленная кожа с металлическими заклепками.',
    },
    pants_iron: {
        id: 'pants_iron',
        name: 'Железные Поножи',
        requiredLevel: 27,
        rarity: 'RARE',
        hpBonus: 354,
        speedBonus: 0.03,
        priceGold: 15000,
        image: '/assets/images/items/pants/pants_iron.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Тяжелые железные пластины для базовой защиты.',
    },

    // EPIC - Полноценные латы
    pants_steel: {
        id: 'pants_steel',
        name: 'Стальные Поножи',
        requiredLevel: 28,
        rarity: 'EPIC',
        hpBonus: 541,
        speedBonus: 0.04,
        priceGem: 350,
        image: '/assets/images/items/pants/pants_steel.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Качественная сталь, выкованная опытным мастером.',
    },
    pants_forest: {
        id: 'pants_forest',
        name: 'Латные Поножи Лесника',
        requiredLevel: 37,
        rarity: 'EPIC',
        hpBonus: 632,
        speedBonus: 0.06,
        priceGem: 650,
        image: '/assets/images/items/pants/pants_forest.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Металлическая защита, адаптированная для лесных боев.',
    },

    // LEGENDARY - Элитная броня
    pants_royal: {
        id: 'pants_royal',
        name: 'Эгида Королевской Гвардии',
        requiredLevel: 47,
        rarity: 'LEGENDARY',
        hpBonus: 1144,
        priceGem: 1500,
        image: '/assets/images/items/pants/pants_royal.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        speedBonus: 0.08,
        desc: 'Золотая отделка и лучшая сталь королевства.',
    },
    pants_bone: {
        id: 'pants_bone',
        name: 'Поножи Костяного Лорда',
        requiredLevel: 55,
        rarity: 'LEGENDARY',
        hpBonus: 1267,
        speedBonus: 0.10,
        priceGem: 2800,
        image: '/assets/images/items/pants/pants_bone.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Темная сталь, пропитанная энергией мертвых.',
    },
    pants_shadow: {
        id: 'pants_shadow',
        name: 'Поножи Ночного Стража',
        requiredLevel: 63,
        rarity: 'LEGENDARY',
        hpBonus: 1389,
        speedBonus: 0.1,
        priceGem: 2200,
        image: '/assets/images/items/pants/pants_shadow.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Острые шипы и вороненая сталь делают владельца невидимым в ночи.',
    },

    // MYTHIC - ТОП (Лучшие латы)
    pants_ragged: {
        id: 'pants_ragged',
        name: 'Поножи Черного Шипа',
        requiredLevel: 64,
        rarity: 'MYTHIC',
        hpBonus: 2040,
        speedBonus: 0.12,
        priceGem: 4500,
        image: '/assets/images/items/pants/pants_ragged.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Легендарные шипастые латы, внушающие ужас врагам.',
    },
    pants_dark: {
        id: 'pants_dark',
        name: 'Латы Падшего Рыцаря',
        requiredLevel: 72,
        rarity: 'MYTHIC',
        hpBonus: 2210,
        speedBonus: 0.15,
        priceGem: 6000,
        image: '/assets/images/items/pants/pants_dark.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Древний доспех великого воина, не знавшего поражений.',
    },
    pants_hunter: {
        id: 'pants_hunter',
        name: 'Поножи Золотого Грифона',
        requiredLevel: 80,
        rarity: 'MYTHIC',
        hpBonus: 2380,
        speedBonus: 0.18,
        priceGem: 7500,
        image: '/assets/images/items/pants/pants_hunter.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Священные золотые латы, сияющие светом небес.',
    },
    pants_titan: {
        id: 'pants_titan',
        name: 'Кольчужные Поножи Гвардейца',
        requiredLevel: 46,
        rarity: 'EPIC',
        hpBonus: 724,
        speedBonus: 0.07,
        priceGem: 1000,
        image: '/assets/images/items/pants/pants_titan.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Надежная кольчужная броня, усиленная стальными наколенниками.',
    },
};
