import { IEquipmentStats } from './types';

export const pants: Record<string, IEquipmentStats> = {
    // COMMON - Ткань и кожа (самые дешевые и слабые)
    pants_mythic: {
        id: 'pants_mythic',
        name: 'Штаны Скитальца',
        defenseBonus: 3,
        hpBonus: 30,
        rarity: 'COMMON',
        priceGold: 200,
        requiredLevel: 1,
        image: '/assets/images/items/pants/pants_mythic.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Простая кожаная одежда, не стесняющая движений.',
    },
    pants_void: {
        id: 'pants_void',
        name: 'Рваные Обноски',
        defenseBonus: 5,
        hpBonus: 50,
        rarity: 'COMMON',
        priceGold: 350,
        requiredLevel: 2,
        image: '/assets/images/items/pants/pants_void.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Старые штаны, которые давно пора пустить на ветошь.',
    },
    pants_storm: {
        id: 'pants_storm',
        name: 'Кожаные Брюки',
        defenseBonus: 10,
        hpBonus: 100,
        rarity: 'COMMON',
        priceGold: 550,
        requiredLevel: 3,
        image: '/assets/images/items/pants/pants_storm.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Обычные брюки из грубой кожи.',
    },
    pants_spiked: {
        id: 'pants_spiked',
        name: 'Брюки Охотника',
        defenseBonus: 15,
        hpBonus: 150,
        rarity: 'COMMON',
        priceGold: 800,
        requiredLevel: 5,
        image: '/assets/images/items/pants/pants_spiked.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Практичная одежда для вылазок в лес.',
    },

    // RARE - Укрепленная кожа и простое железо
    pants_mercenary: {
        id: 'pants_mercenary',
        name: 'Поножи Наемника',
        priceGold: 5000,
        requiredLevel: 12,
        image: '/assets/images/items/pants/pants_mercenary.webp',
        rarity: 'RARE',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        defenseBonus: 40,
        speedBonus: 0.03,
        hpBonus: 400,
        desc: 'Укрепленная кожа с металлическими заклепками.',
    },
    pants_iron: {
        id: 'pants_iron',
        name: 'Железные Поножи',
        defenseBonus: 60,
        hpBonus: 600,
        rarity: 'RARE',
        priceGold: 15000,
        requiredLevel: 18,
        image: '/assets/images/items/pants/pants_iron.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Тяжелые железные пластины для базовой защиты.',
    },

    // EPIC - Полноценные латы
    pants_steel: {
        id: 'pants_steel',
        name: 'Стальные Поножи',
        defenseBonus: 75,
        hpBonus: 750,
        rarity: 'EPIC',
        priceGem: 350,
        requiredLevel: 28,
        image: '/assets/images/items/pants/pants_steel.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Качественная сталь, выкованная опытным мастером.',
    },
    pants_forest: {
        id: 'pants_forest',
        name: 'Латные Поножи Лесника',
        defenseBonus: 110,
        hpBonus: 1100,
        rarity: 'EPIC',
        priceGem: 650,
        requiredLevel: 35,
        image: '/assets/images/items/pants/pants_forest.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Металлическая защита, адаптированная для лесных боев.',
    },

    // LEGENDARY - Элитная броня
    pants_royal: {
        id: 'pants_royal',
        name: 'Эгида Королевской Гвардии',
        priceGem: 1500,
        requiredLevel: 50,
        image: '/assets/images/items/pants/pants_royal.webp',
        rarity: 'LEGENDARY',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        defenseBonus: 250,
        hpBonus: 2500,
        desc: 'Золотая отделка и лучшая сталь королевства.',
    },
    pants_bone: {
        id: 'pants_bone',
        name: 'Поножи Костяного Лорда',
        defenseBonus: 350,
        hpBonus: 3500,
        rarity: 'LEGENDARY',
        priceGem: 2800,
        requiredLevel: 57,
        image: '/assets/images/items/pants/pants_bone.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Темная сталь, пропитанная энергией мертвых.',
    },
    pants_shadow: {
        id: 'pants_shadow',
        name: 'Поножи Ночного Стража',
        defenseBonus: 300,
        hpBonus: 3000,
        speedBonus: 0.1,
        rarity: 'LEGENDARY',
        priceGem: 2200,
        requiredLevel: 54,
        image: '/assets/images/items/pants/pants_shadow.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Острые шипы и вороненая сталь делают владельца невидимым в ночи.',
    },

    // MYTHIC - ТОП (Лучшие латы)
    pants_ragged: {
        id: 'pants_ragged',
        name: 'Поножи Черного Шипа',
        defenseBonus: 420,
        hpBonus: 4200,
        rarity: 'MYTHIC',
        priceGem: 4500,
        requiredLevel: 65,
        image: '/assets/images/items/pants/pants_ragged.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Легендарные шипастые латы, внушающие ужас врагам.',
    },
    pants_dark: {
        id: 'pants_dark',
        name: 'Латы Падшего Рыцаря',
        defenseBonus: 580,
        hpBonus: 5800,
        rarity: 'MYTHIC',
        priceGem: 6000,
        requiredLevel: 72,
        image: '/assets/images/items/pants/pants_dark.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Древний доспех великого воина, не знавшего поражений.',
    },
    pants_hunter: {
        id: 'pants_hunter',
        name: 'Поножи Золотого Грифона',
        defenseBonus: 750,
        hpBonus: 7500,
        rarity: 'MYTHIC',
        priceGem: 7500,
        requiredLevel: 80,
        image: '/assets/images/items/pants/pants_hunter.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Священные золотые латы, сияющие светом небес.',
    },
    pants_titan: {
        id: 'pants_titan',
        name: 'Кольчужные Поножи Гвардейца',
        defenseBonus: 150,
        hpBonus: 1500,
        rarity: 'EPIC',
        priceGem: 1000,
        requiredLevel: 42,
        image: '/assets/images/items/pants/pants_titan.webp',
        mainTab: 'ARSENAL',
        subTab: 'PANTS',
        desc: 'Надежная кольчужная броня, усиленная стальными наколенниками.',
    },
};
