import { IEquipmentStats } from './types';

export const shields: Record<string, IEquipmentStats> = {
    starter_shield: {
        id: 'starter_shield',
        name: 'Деревянный Баклер',
        defenseBonus: 5,
        hpBonus: 50,
        rarity: 'COMMON',
        priceGold: 120,
        requiredLevel: 1,
        image: '/assets/images/items/shields/starter_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Маленький щит из досок.',
    },
    shield_plank: {
        id: 'shield_plank',
        name: 'Дощатый Щит',
        defenseBonus: 12,
        hpBonus: 120,
        rarity: 'COMMON',
        priceGold: 700,
        requiredLevel: 3,
        image: '/assets/images/items/shields/plank_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Прочный щит из дубовых досок.',
    },
    shield_iron: {
        id: 'shield_iron',
        name: 'Железный Щит',
        defenseBonus: 40,
        hpBonus: 400,
        rarity: 'RARE',
        priceGold: 8000,
        requiredLevel: 12,
        image: '/assets/images/items/shields/dented_buckler.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Надежная железная защита.',
    },
    shield_steel: {
        id: 'shield_steel',
        name: 'Стальной Щит',
        defenseBonus: 90,
        hpBonus: 900,
        rarity: 'EPIC',
        priceGem: 500,
        requiredLevel: 30,
        image: '/assets/images/items/shields/steel_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Выкован из каленой стали.',
    },
    shield_dragon: {
        id: 'shield_dragon',
        name: 'Бастион Древнего Дракона',
        defenseBonus: 300,
        hpBonus: 3000,
        rarity: 'LEGENDARY',
        priceGem: 2200,
        requiredLevel: 55,
        image: '/assets/images/items/shields/bone_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Чешуя древнего ящера, закаленная тысячелетиями в пламени.',
    },
    royal_shield: {
        id: 'royal_shield',
        name: 'Эгида Солнечного Короля',
        priceGem: 6000,
        requiredLevel: 75,
        image: '/assets/images/items/shields/royal_shield.webp',
        rarity: 'MYTHIC',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        textureKey: 'shield_royal',
        defenseBonus: 620,
        hpBonus: 6200,
        desc: 'Золотой щит, отражающий свет самой истины.',
    },
    shield_lesnogo_strazha: {
        id: 'shield_lesnogo_strazha',
        name: 'Щит Лесного Стража',
        defenseBonus: 18,
        hpBonus: 180,
        rarity: 'COMMON',
        priceGold: 1500,
        requiredLevel: 5,
        image: '/assets/images/items/shields/shield_lesnogo_strazha.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Сплетенный из вековых лоз и укрепленный дубовой корой.',
    },
    bronzovyy_target: {
        id: 'bronzovyy_target',
        name: 'Бронзовый Таргет',
        defenseBonus: 48,
        hpBonus: 480,
        rarity: 'RARE',
        priceGold: 10000,
        requiredLevel: 14,
        image: '/assets/images/items/shields/bronzovyy_target.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Легкий бронзовый щит, украшенный гравировкой солнца.',
    },
    shield_ohotnika_na_trolley: {
        id: 'shield_ohotnika_na_trolley',
        name: 'Щит Охотника на Троллей',
        defenseBonus: 56,
        hpBonus: 560,
        rarity: 'RARE',
        priceGem: 500,
        requiredLevel: 16,
        image: '/assets/images/items/shields/shield_ohotnika_na_trolley.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Прочный ростовой щит с окованными краями для защиты от дубин.',
    },
    runicheskiy_shield_gor: {
        id: 'runicheskiy_shield_gor',
        name: 'Рунический Щит Гор',
        defenseBonus: 64,
        hpBonus: 640,
        rarity: 'RARE',
        priceGold: 18000,
        requiredLevel: 18,
        image: '/assets/images/items/shields/runicheskiy_shield_gor.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Высеченные на граните руны поглощают кинетическую энергию ударов.',
    },
    shield_kamennogo_golema: {
        id: 'shield_kamennogo_golema',
        name: 'Щит Каменного Голема',
        defenseBonus: 110,
        hpBonus: 1100,
        rarity: 'EPIC',
        priceGold: 35000,
        requiredLevel: 28,
        image: '/assets/images/items/shields/shield_kamennogo_golema.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Тяжелая каменная плита, оживленная частицей магии земли.',
    },
    barier_grozovogo_maga: {
        id: 'barier_grozovogo_maga',
        name: 'Барьер Грозового Мага',
        defenseBonus: 140,
        hpBonus: 1400,
        speedBonus: 0.05,
        rarity: 'EPIC',
        priceGem: 650,
        requiredLevel: 33,
        image: '/assets/images/items/shields/barier_grozovogo_maga.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Окружен искрящимся электрическим полем, ускоряющим реакцию.',
    },
    shield_pepelnogo_rycarya: {
        id: 'shield_pepelnogo_rycarya',
        name: 'Щит Пепельного Рыцаря',
        defenseBonus: 175,
        hpBonus: 1750,
        rarity: 'EPIC',
        priceGold: 55000,
        requiredLevel: 38,
        image: '/assets/images/items/shields/shield_pepelnogo_rycarya.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Закаленный в пламени угасающего костра, хранит пепел павших товарищей.',
    },
    shield_krovavoy_luny: {
        id: 'shield_krovavoy_luny',
        name: 'Щит Кровавой Луны',
        defenseBonus: 220,
        hpBonus: 2200,
        critBonus: 0.05,
        rarity: 'EPIC',
        priceGem: 900,
        requiredLevel: 43,
        image: '/assets/images/items/shields/shield_krovavoy_luny.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Алый свет луны наполняет владельца жаждой возмездия при блокировании.',
    },
    oplot_ledyanogo_korolya: {
        id: 'oplot_ledyanogo_korolya',
        name: 'Оплот Ледяного Короля',
        defenseBonus: 360,
        hpBonus: 3600,
        rarity: 'LEGENDARY',
        priceGem: 2800,
        requiredLevel: 57,
        image: '/assets/images/items/shields/oplot_ledyanogo_korolya.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Легендарный щит из нетающего вечного льда северных пустошей.',
    },
};
