import { IEquipmentStats } from './types';

export const shields: Record<string, IEquipmentStats> = {
    starter_shield: {
        id: 'starter_shield',
        name: 'Деревянный Баклер',
        defenseBonus: 5,
        hpBonus: 50,
        rarity: 'COMMON',
        priceGold: 120,
        requiredLevel: 1,
        image: '/assets/images/items/shields/starter_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Маленький щит из досок.',
    },
    shield_plank: {
        id: 'shield_plank',
        name: 'Дощатый Щит',
        defenseBonus: 12,
        hpBonus: 120,
        rarity: 'COMMON',
        priceGold: 700,
        requiredLevel: 3,
        image: '/assets/images/items/shields/plank_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Прочный щит из дубовых досок.',
    },
    shield_iron: {
        id: 'shield_iron',
        name: 'Железный Щит',
        defenseBonus: 40,
        hpBonus: 400,
        rarity: 'RARE',
        priceGold: 8000,
        requiredLevel: 12,
        image: '/assets/images/items/shields/dented_buckler.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Надежная железная защита.',
    },
    shield_steel: {
        id: 'shield_steel',
        name: 'Стальной Щит',
        defenseBonus: 90,
        hpBonus: 900,
        rarity: 'EPIC',
        priceGem: 500,
        requiredLevel: 30,
        image: '/assets/images/items/shields/steel_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Выкован из каленой стали.',
    },
    shield_dragon: {
        id: 'shield_dragon',
        name: 'Бастион Древнего Дракона',
        defenseBonus: 300,
        hpBonus: 3000,
        rarity: 'LEGENDARY',
        priceGem: 2200,
        requiredLevel: 55,
        image: '/assets/images/items/shields/bone_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Чешуя древнего ящера, закаленная тысячелетиями в пламени.',
    },
    royal_shield: {
        id: 'royal_shield',
        name: 'Эгида Солнечного Короля',
        priceGem: 6000,
        requiredLevel: 75,
        image: '/assets/images/items/shields/royal_shield.webp',
        rarity: 'MYTHIC',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        textureKey: 'shield_royal',
        defenseBonus: 620,
        hpBonus: 6200,
        desc: 'Золотой щит, отражающий свет самой истины.',
    },
};
