import { IEquipmentStats } from './types';

export const shields: Record<string, IEquipmentStats> = {
    starter_shield: {
        id: 'starter_shield',
        name: 'Деревянный Баклер',
        requiredLevel: 1,
        rarity: 'COMMON',
        defenseBonus: 9,
        hpBonus: 90,
        priceGold: 1800,
        image: '/assets/images/items/shields/starter_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Маленький щит из досок.',
    },

    shield_lesnogo_strazha: {
        id: 'shield_lesnogo_strazha',
        name: 'Щит Лесного Стража',
        requiredLevel: 5,
        rarity: 'COMMON',
        defenseBonus: 15,
        hpBonus: 150,
        priceGem: 18,
        image: '/assets/images/items/shields/shield_lesnogo_strazha.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Сплетенный из вековых лоз и укрепленный дубовой корой.',
    },

    shield_plank: {
        id: 'shield_plank',
        name: 'Дощатый Щит',
        requiredLevel: 10,
        rarity: 'COMMON',
        defenseBonus: 25,
        hpBonus: 250,
        priceGold: 7000,
        image: '/assets/images/items/shields/plank_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Прочный щит из дубовых досок.',
    },

    bronzovyy_target: {
        id: 'bronzovyy_target',
        name: 'Бронзовый Таргет',
        requiredLevel: 11,
        rarity: 'RARE',
        defenseBonus: 27,
        hpBonus: 270,
        priceGem: 70,
        image: '/assets/images/items/shields/bronzovyy_target.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Легкий бронзовый щит, украшенный гравировкой солнца.',
    },

    shield_iron: {
        id: 'shield_iron',
        name: 'Железный Щит',
        requiredLevel: 16,
        rarity: 'RARE',
        defenseBonus: 39,
        hpBonus: 390,
        priceGold: 19000,
        image: '/assets/images/items/shields/dented_buckler.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Надежная железная защита.',
    },

    shield_ohotnika_na_trolley: {
        id: 'shield_ohotnika_na_trolley',
        name: 'Щит Охотника на Троллей',
        requiredLevel: 22,
        rarity: 'RARE',
        defenseBonus: 55,
        hpBonus: 550,
        priceGem: 190,
        image: '/assets/images/items/shields/shield_ohotnika_na_trolley.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Прочный ростовой щит с окованными краями для защиты от дубин.',
    },

    runicheskiy_shield_gor: {
        id: 'runicheskiy_shield_gor',
        name: 'Рунический Щит Гор',
        requiredLevel: 27,
        rarity: 'RARE',
        defenseBonus: 70,
        hpBonus: 700,
        priceGold: 45000,
        image: '/assets/images/items/shields/runicheskiy_shield_gor.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Высеченные на граните руны поглощают кинетическую энергию ударов.',
    },

    shield_kamennogo_golema: {
        id: 'shield_kamennogo_golema',
        name: 'Щит Каменного Голема',
        requiredLevel: 28,
        rarity: 'EPIC',
        defenseBonus: 73,
        hpBonus: 730,
        priceGem: 450,
        image: '/assets/images/items/shields/shield_kamennogo_golema.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Тяжелая каменная плита, оживленная частицей магии земли.',
    },

    shield_steel: {
        id: 'shield_steel',
        name: 'Стальной Щит',
        requiredLevel: 33,
        rarity: 'EPIC',
        defenseBonus: 88,
        hpBonus: 880,
        priceGold: 62000,
        image: '/assets/images/items/shields/steel_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Выкован из каленой стали.',
    },

    barier_grozovogo_maga: {
        id: 'barier_grozovogo_maga',
        name: 'Барьер Грозового Мага',
        requiredLevel: 37,
        rarity: 'EPIC',
        defenseBonus: 100,
        hpBonus: 1000,
        priceGem: 780,
        image: '/assets/images/items/shields/barier_grozovogo_maga.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Окружен искрящимся электрическим полем, ускоряющим реакцию.',
    },

    shield_krovavoy_luny: {
        id: 'shield_krovavoy_luny',
        name: 'Щит Кровавой Луны',
        requiredLevel: 42,
        rarity: 'EPIC',
        defenseBonus: 116,
        hpBonus: 1160,
        priceGold: 80000,
        image: '/assets/images/items/shields/shield_krovavoy_luny.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Алый свет луны наполняет владельца жаждой возмездия при блокировании.',
    },

    shield_pepelnogo_rycarya: {
        id: 'shield_pepelnogo_rycarya',
        name: 'Щит Пепельного Рыцаря',
        requiredLevel: 46,
        rarity: 'EPIC',
        defenseBonus: 129,
        hpBonus: 1290,
        priceGem: 1050,
        image: '/assets/images/items/shields/shield_pepelnogo_rycarya.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Закаленный в пламени угасающего костра, хранит пепел павших товарищей.',
    },

    shield_dragon: {
        id: 'shield_dragon',
        name: 'Бастион Древнего Дракона',
        requiredLevel: 47,
        rarity: 'LEGENDARY',
        defenseBonus: 133,
        hpBonus: 1330,
        priceGold: 108000,
        image: '/assets/images/items/shields/bone_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Чешуя древнего ящера, закаленная тысячелетиями в пламени.',
    },

    oplot_ledyanogo_korolya: {
        id: 'oplot_ledyanogo_korolya',
        name: 'Оплот Ледяного Короля',
        requiredLevel: 63,
        rarity: 'LEGENDARY',
        defenseBonus: 188,
        hpBonus: 1880,
        priceGem: 1300,
        image: '/assets/images/items/shields/oplot_ledyanogo_korolya.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Легендарный щит из нетающего вечного льда северных пустошей.',
    },

    royal_shield: {
        id: 'royal_shield',
        name: 'Эгида Солнечного Короля',
        requiredLevel: 80,
        rarity: 'MYTHIC',
        defenseBonus: 252,
        hpBonus: 2520,
        priceGold: 145000,
        image: '/assets/images/items/shields/royal_shield.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHIELDS',
        desc: 'Золотой щит, отражающий свет самой истины.',
        textureKey: 'shield_royal',
    },
};
