import { IEquipmentStats } from './types';

export const shoulders: Record<string, IEquipmentStats> = {
    sh_fire_lion: {
        id: 'sh_fire_lion',
        name: 'Плащ Огненного Короля',
        priceGem: 1500,
        image: '/assets/images/items/shoulders/shoulders_5.png',
        rarity: 'MYTHIC',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        attackBonus: 50,
        defenseBonus: 20,
        desc: 'Из пастей львов вырывается неугасающий огонь древних королей.',
    },
    sh_acid_spikes: {
        id: 'sh_acid_spikes',
        name: 'Шипы Изумрудного Яда',
        priceGold: 25000,
        image: '/assets/images/items/shoulders/shoulders_4.png',
        rarity: 'EPIC',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        defenseBonus: 30,
        critBonus: 0.05,
        desc: 'Пропитаны ядом древних змей.',
    },
    sh_bone_lord: {
        id: 'sh_bone_lord',
        name: 'Оплечье Владыки Склепа',
        priceGem: 800,
        image: '/assets/images/items/shoulders/shoulders_3.png',
        rarity: 'EPIC',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        defenseBonus: 40,
        hpBonus: 500,
        desc: 'Кости содрогаются от темной магии.',
    },
    sh_frost_shards: {
        id: 'sh_frost_shards',
        name: 'Осколки Вечного Льда',
        priceGold: 15000,
        image: '/assets/images/items/shoulders/shoulders_2.png',
        rarity: 'RARE',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        defenseBonus: 25,
        speedBonus: -0.02,
        desc: 'Холод этих наплечников замедляет врагов.',
    },
    sh_steam_gear: {
        id: 'sh_steam_gear',
        name: 'Механизм Высшей Паровой Лиги',
        priceGold: 45000,
        image: '/assets/images/items/shoulders/shoulders_1.png',
        rarity: 'EPIC',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        defenseBonus: 45,
        speedBonus: 0.05,
        desc: 'Поршни и шестерни усиливают каждое движение.',
    },
    sh_void_walker: {
        id: 'sh_void_walker',
        name: 'Лик Космической Тьмы',
        priceGem: 2500,
        image: '/assets/images/items/shoulders/shoulders_6.png',
        rarity: 'LEGENDARY',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        defenseBonus: 100,
        hpBonus: 2000,
        desc: 'В этих наплечниках запечатана сама пустота мироздания.',
    },
    sh_nature_spirit: {
        id: 'sh_nature_spirit',
        name: 'Оплечье Хранителя Рощи',
        priceGold: 12000,
        image: '/assets/images/items/shoulders/shoulders_7.png',
        rarity: 'RARE',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        hpBonus: 600,
        defenseBonus: 15,
        desc: 'Живое дерево продолжает расти прямо на доспехе.',
    },
    sh_golden_lion: {
        id: 'sh_golden_lion',
        name: 'Наплечники Золотого Императора',
        priceGem: 3000,
        image: '/assets/images/items/shoulders/shoulders_8.png',
        rarity: 'LEGENDARY',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        defenseBonus: 150,
        hpBonus: 3500,
        desc: 'Священный металл, достойный лишь правителя джунглей.',
    },
};
