import { IEquipmentStats } from './types';

export const shoulders: Record<string, IEquipmentStats> = {
    sh_frost_shards: {
        id: 'sh_frost_shards',
        name: 'Осколки Вечного Льда',
        requiredLevel: 11,
        rarity: 'RARE',
        attackBonus: 9,
        defenseBonus: 14,
        hpBonus: 140,
        priceGold: 9000,
        image: '/assets/images/items/shoulders/shoulders_2.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Холод этих наплечников замедляет врагов.',
    },

    sh_nature_spirit: {
        id: 'sh_nature_spirit',
        name: 'Оплечье Хранителя Рощи',
        requiredLevel: 27,
        rarity: 'RARE',
        attackBonus: 21,
        defenseBonus: 34,
        hpBonus: 340,
        priceGem: 310,
        image: '/assets/images/items/shoulders/shoulders_7.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Живое дерево продолжает расти прямо на доспехе.',
    },

    sh_acid_spikes: {
        id: 'sh_acid_spikes',
        name: 'Шипы Изумрудного Яда',
        requiredLevel: 28,
        rarity: 'EPIC',
        attackBonus: 22,
        defenseBonus: 36,
        hpBonus: 360,
        priceGold: 40000,
        image: '/assets/images/items/shoulders/shoulders_4.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Пропитаны ядом древних змей.',
    },

    sh_bone_lord: {
        id: 'sh_bone_lord',
        name: 'Оплечье Владыки Склепа',
        requiredLevel: 37,
        rarity: 'EPIC',
        attackBonus: 31,
        defenseBonus: 51,
        hpBonus: 510,
        priceGem: 700,
        image: '/assets/images/items/shoulders/shoulders_3.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Кости содрогаются от темной магии.',
    },

    sh_steam_gear: {
        id: 'sh_steam_gear',
        name: 'Механизм Высшей Паровой Лиги',
        requiredLevel: 46,
        rarity: 'EPIC',
        attackBonus: 41,
        defenseBonus: 68,
        hpBonus: 680,
        priceGold: 72000,
        image: '/assets/images/items/shoulders/shoulders_1.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Поршни и шестерни усиливают каждое движение.',
    },

    sh_void_walker: {
        id: 'sh_void_walker',
        name: 'Лик Космической Тьмы',
        requiredLevel: 47,
        rarity: 'LEGENDARY',
        attackBonus: 42,
        defenseBonus: 70,
        hpBonus: 700,
        priceGem: 950,
        image: '/assets/images/items/shoulders/shoulders_6.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'В этих наплечниках запечатана сама пустота мироздания.',
    },

    sh_golden_lion: {
        id: 'sh_golden_lion',
        name: 'Наплечники Золотого Императора',
        requiredLevel: 63,
        rarity: 'LEGENDARY',
        attackBonus: 62,
        defenseBonus: 102,
        hpBonus: 1020,
        priceGold: 100000,
        image: '/assets/images/items/shoulders/shoulders_8.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Священный металл, достойный лишь правителя джунглей.',
    },

    sh_fire_lion: {
        id: 'sh_fire_lion',
        name: 'Плащ Огненного Короля',
        requiredLevel: 80,
        rarity: 'MYTHIC',
        attackBonus: 84,
        defenseBonus: 140,
        hpBonus: 1400,
        priceGem: 1350,
        image: '/assets/images/items/shoulders/shoulders_5.webp',
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Из пастей львов вырывается неугасающий огонь древних королей.',
    },
};
