import { IEquipmentStats } from './types';

export const shoulders: Record<string, IEquipmentStats> = {
    sh_frost_shards: {
        id: 'sh_frost_shards',
        name: 'Осколки Вечного Льда',
        priceGold: 5000,
        requiredLevel: 12,
        image: '/assets/images/items/shoulders/shoulders_2.webp',
        rarity: 'RARE',
        defenseBonus: 15,
        hpBonus: 148,
        attackBonus: 9,
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Холод этих наплечников замедляет врагов.',
    },
    sh_nature_spirit: {
        id: 'sh_nature_spirit',
        name: 'Оплечье Хранителя Рощи',
        priceGold: 14000,
        requiredLevel: 17,
        image: '/assets/images/items/shoulders/shoulders_7.webp',
        rarity: 'RARE',
        defenseBonus: 17,
        hpBonus: 168,
        attackBonus: 10,
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Живое дерево продолжает расти прямо на доспехе.',
    },
    sh_acid_spikes: {
        id: 'sh_acid_spikes',
        name: 'Шипы Изумрудного Яда',
        priceGem: 350,
        requiredLevel: 28,
        image: '/assets/images/items/shoulders/shoulders_4.webp',
        rarity: 'EPIC',
        defenseBonus: 32,
        hpBonus: 318,
        attackBonus: 19,
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Пропитаны ядом древних змей.',
    },
    sh_bone_lord: {
        id: 'sh_bone_lord',
        name: 'Оплечье Владыки Склепа',
        priceGem: 700,
        requiredLevel: 35,
        image: '/assets/images/items/shoulders/shoulders_3.webp',
        rarity: 'EPIC',
        defenseBonus: 36,
        hpBonus: 360,
        attackBonus: 22,
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Кости содрогаются от темной магии.',
    },
    sh_steam_gear: {
        id: 'sh_steam_gear',
        name: 'Механизм Высшей Паровой Лиги',
        priceGem: 1100,
        requiredLevel: 42,
        image: '/assets/images/items/shoulders/shoulders_1.webp',
        rarity: 'EPIC',
        defenseBonus: 40,
        hpBonus: 402,
        attackBonus: 24,
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Поршни и шестерни усиливают каждое движение.',
    },
    sh_void_walker: {
        id: 'sh_void_walker',
        name: 'Лик Космической Тьмы',
        priceGem: 1800,
        requiredLevel: 52,
        image: '/assets/images/items/shoulders/shoulders_6.webp',
        rarity: 'LEGENDARY',
        defenseBonus: 72,
        hpBonus: 718,
        attackBonus: 43,
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'В этих наплечниках запечатана сама пустота мироздания.',
    },
    sh_golden_lion: {
        id: 'sh_golden_lion',
        name: 'Наплечники Золотого Императора',
        priceGem: 3200,
        requiredLevel: 58,
        image: '/assets/images/items/shoulders/shoulders_8.webp',
        rarity: 'LEGENDARY',
        defenseBonus: 77,
        hpBonus: 772,
        attackBonus: 46,
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Священный металл, достойный лишь правителя джунглей.',
    },
    sh_fire_lion: {
        id: 'sh_fire_lion',
        name: 'Плащ Огненного Короля',
        priceGem: 6500,
        requiredLevel: 72,
        image: '/assets/images/items/shoulders/shoulders_5.webp',
        rarity: 'MYTHIC',
        defenseBonus: 130,
        hpBonus: 1300,
        attackBonus: 78,
        mainTab: 'ARSENAL',
        subTab: 'SHOULDERS',
        desc: 'Из пастей львов вырывается неугасающий огонь древних королей.',
    },
};
