import { IEquipmentStats } from './types';

export const weapons: Record<string, IEquipmentStats> = {
    // COMMON - Уровень 1-5
    sling_leather: {
        id: 'sling_leather',
        name: 'Кожаная Праща',
        requiredLevel: 3,
        rarity: 'COMMON',
        attackBonus: 35,
        priceGold: 200,
        image: '/assets/images/items/weapons/sling.webp',
        atlasFrame: 'sling.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простое метательное оружие из полоски кожи.',
    },
    // Стартовое оружие (id: stick — выдаётся в начале игры)
    stick: {
        id: 'stick',
        name: 'Бамбуковая Палка',
        requiredLevel: 1,
        rarity: 'COMMON',
        attackBonus: 32,
        priceGold: 100,
        image: '/assets/images/items/weapons/stick.webp',
        atlasFrame: 'stick.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простая бамбуковая палка. Не самое грозное оружие, но с чего-то надо начинать.',
    },
    stick_oak: {
        id: 'stick_oak',
        name: 'Дубовый Посох',
        requiredLevel: 10,
        rarity: 'COMMON',
        attackBonus: 45,
        speedBonus: 0.05,
        priceGold: 300,
        image: '/assets/images/items/weapons/staff.webp',
        atlasFrame: 'staff.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простой деревянный посох для начинающих магов.',
    },

    pan_master: {
        id: 'pan_master',
        name: 'Чугунная Сковорода',
        requiredLevel: 5,
        rarity: 'COMMON',
        attackBonus: 38,
        priceGold: 400,
        image: '/assets/images/items/weapons/pan.webp',
        atlasFrame: 'pan.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Тяжелая, надежная и отлично звонит при ударе.',
    },
    // RARE - Уровень 10-20
    sword_broken: {
        id: 'sword_broken',
        name: 'Обломок Катаны',
        requiredLevel: 14,
        rarity: 'RARE',
        attackBonus: 94,
        speedBonus: 0.08,
        priceGold: 2000,
        image: '/assets/images/items/weapons/broken_sword.webp',
        atlasFrame: 'broken_sword.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Даже в сломанном виде эта сталь остается невероятно острой.',
    },
    dagger_rusty: {
        id: 'dagger_rusty',
        name: 'Ржавый Тесак',
        requiredLevel: 11,
        rarity: 'RARE',
        attackBonus: 86,
        critBonus: 0.03,
        priceGold: 3500,
        image: '/assets/images/items/weapons/rusty_dagger.webp',
        atlasFrame: 'rusty_dagger.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Старое лезвие, побитое временем и ржавчиной.',
    },
    dagger_bone: {
        id: 'dagger_bone',
        name: 'Клык Кровавого Жнеца',
        requiredLevel: 16,
        rarity: 'RARE',
        attackBonus: 98,
        critBonus: 0.03,
        priceGold: 6000,
        image: '/assets/images/items/weapons/wa11413pons_sheet.webp',
        atlasFrame: 'wa11413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Костяной кинжал с навершием в виде черепа.',
    },
    staff_willow: {
        id: 'staff_willow',
        name: 'Ивовый Жезл Очищения',
        requiredLevel: 22,
        rarity: 'RARE',
        attackBonus: 113,
        speedBonus: 0.07,
        priceGold: 8000,
        image: '/assets/images/items/weapons/staff.webp',
        atlasFrame: 'staff.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Жезл из ветви священной ивы, наполненный энергией природы.',
    },
    dagger_ritual: {
        id: 'dagger_ritual',
        name: 'Кинжал Забытых Предков',
        requiredLevel: 19,
        rarity: 'RARE',
        attackBonus: 106,
        critBonus: 0.04,
        priceGold: 10000,
        image: '/assets/images/items/weapons/wa141413pons_sheet.webp',
        atlasFrame: 'wa141413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Древнее костяное лезвие с магическими рунами.',
    },
    bow_composite: {
        id: 'bow_composite',
        name: 'Композитный Лук Волка',
        requiredLevel: 27,
        rarity: 'RARE',
        attackBonus: 125,
        critBonus: 0.03,
        speedBonus: 0.05,
        priceGold: 18000,
        image: '/assets/images/items/weapons/bow.webp',
        atlasFrame: 'bow.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Эргономичный лук, обеспечивающий высокую точность стрельбы.',
    },
    axe_iron: {
        id: 'axe_iron',
        name: 'Секира Лесного Ополченца',
        requiredLevel: 24,
        rarity: 'RARE',
        attackBonus: 118,
        critBonus: 0.04,
        priceGold: 25000,
        image: '/assets/images/items/weapons/wa1441413pons_sheet.webp',
        atlasFrame: 'wa1441413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простой, но надежный топор для защиты своего дома.',
    },

    // EPIC - Уровень 25-45
    katana_shadow: {
        id: 'katana_shadow',
        name: 'Катана Тени',
        requiredLevel: 28,
        rarity: 'EPIC',
        attackBonus: 191,
        speedBonus: 0.1,
        priceGem: 300,
        image: '/assets/images/items/weapons/a113ons_sheet.webp',
        atlasFrame: 'a113ons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Клинок, который практически не виден в темноте.',
    },
    katana_steel: {
        id: 'katana_steel',
        name: 'Стальная Катана',
        requiredLevel: 30,
        rarity: 'EPIC',
        attackBonus: 198,
        speedBonus: 0.10,
        priceGem: 350,
        image: '/assets/images/items/weapons/a1ons_sheet.webp',
        atlasFrame: 'a1ons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Классическое оружие, доведенное до совершенства.',
    },
    katana_blood: {
        id: 'katana_blood',
        name: 'Катана Кровавой Луны',
        requiredLevel: 41,
        rarity: 'EPIC',
        attackBonus: 238,
        critBonus: 0.05,
        priceGem: 420,
        image: '/assets/images/items/weapons/a13ons_sheet.webp',
        atlasFrame: 'a13ons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Её лезвие жаждет битвы так же сильно, как и её владелец.',
    },
    mace_justice: {
        id: 'mace_justice',
        name: 'Булава Правосудия',
        requiredLevel: 32,
        rarity: 'EPIC',
        attackBonus: 205,
        speedBonus: 0.08,
        priceGem: 480,
        image: '/assets/images/items/weapons/a113pons_sheet.webp',
        atlasFrame: 'a113pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Каждый удар этой булавы несет в себе тяжесть закона.',
    },
    staff_shadow: {
        id: 'staff_shadow',
        name: 'Посох Теневого Мага',
        requiredLevel: 42,
        rarity: 'EPIC',
        attackBonus: 241,
        speedBonus: 0.10,
        priceGem: 560,
        image: '/assets/images/items/weapons/void_staff.webp',
        atlasFrame: 'void_staff.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Позволяет манипулировать энергией тени.',
    },
    daggers_assassin: {
        id: 'daggers_assassin',
        name: 'Кинжалы Убийцы',
        requiredLevel: 37,
        rarity: 'EPIC',
        attackBonus: 223,
        speedBonus: 0.15,
        priceGem: 600,
        image: '/assets/images/items/weapons/daggers.webp',
        atlasFrame: 'daggers.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Пара быстрых клинков для тех, кто не привык ждать.',
    },
    axe_executioner: {
        id: 'axe_executioner',
        name: 'Секира Палача',
        requiredLevel: 33,
        rarity: 'EPIC',
        attackBonus: 209,
        speedBonus: 0.09,
        priceGem: 700,
        image: '/assets/images/items/weapons/a1113pons_sheet.webp',
        atlasFrame: 'a1113pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Тяжелый топор, предназначенный для одного решающего удара.',
    },
    flail_guardian: {
        id: 'flail_guardian',
        name: 'Моргенштерн Стража',
        requiredLevel: 39,
        rarity: 'EPIC',
        attackBonus: 230,
        speedBonus: 0.10,
        priceGem: 800,
        image: '/assets/images/items/weapons/a11413pons_sheet.webp',
        atlasFrame: 'a11413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Шипастый шар на цепи — кошмар любого щитоносца.',
    },
    sword_silver: {
        id: 'sword_silver',
        name: 'Меч Серебряного Рыцаря',
        requiredLevel: 44,
        rarity: 'EPIC',
        attackBonus: 248,
        priceGem: 900,
        image: '/assets/images/items/weapons/moon_sword.webp',
        atlasFrame: 'moon_sword.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Благородный клинок из лучшей стали империи.',
    },
    axe_veteran: {
        id: 'axe_veteran',
        name: 'Боевой Топор Ветерана',
        requiredLevel: 35,
        rarity: 'EPIC',
        attackBonus: 216,
        critBonus: 0.06,
        priceGem: 1000,
        image: '/assets/images/items/weapons/heavy_war_axe.webp',
        atlasFrame: 'heavy_war_axe.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Оружие, прошедшее через сотни сражений.',
    },
    weapon_moon_sword: {
        id: 'weapon_moon_sword',
        name: 'Эпический Меч Луны',
        requiredLevel: 46,
        rarity: 'EPIC',
        attackBonus: 256,
        critBonus: 0.08,
        priceGem: 1200,
        image: '/assets/images/items/weapons/moon_sword.webp',
        atlasFrame: 'moon_sword.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Овеянный легендами клинок, вобравший в себя холодное сияние ночной луны.',
    },

    // LEGENDARY - Уровень 50-60
    bow_griffin: {
        id: 'bow_griffin',
        name: 'Лук Золотого Грифона',
        requiredLevel: 47,
        rarity: 'LEGENDARY',
        attackBonus: 404,
        critBonus: 0.03,
        speedBonus: 0.05,
        priceGem: 1500,
        image: '/assets/images/items/weapons/bow.webp',
        atlasFrame: 'bow.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Тетива этого лука поет, когда стрела летит точно в цель.',
    },
    staff_celestial: {
        id: 'staff_celestial',
        name: 'Жезл Небесного Ока',
        requiredLevel: 51,
        rarity: 'LEGENDARY',
        attackBonus: 425,
        speedBonus: 0.12,
        priceGem: 2000,
        image: '/assets/images/items/weapons/wea231414ons_sprite.webp',
        atlasFrame: 'wea231414ons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Направляет энергию чистого света на противников.',
    },
    hammer_phoenix: {
        id: 'hammer_phoenix',
        name: 'Молот Пылающего Феникса',
        requiredLevel: 59,
        rarity: 'LEGENDARY',
        attackBonus: 469,
        critBonus: 0.08,
        priceGem: 2500,
        image: '/assets/images/items/weapons/phoenix_hammer.webp',
        atlasFrame: 'phoenix_hammer.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Удары этого молота вызывают вспышки священного огня.',
    },
    staff_gold: {
        id: 'staff_gold',
        name: 'Посох Золотого Оракула',
        requiredLevel: 63,
        rarity: 'LEGENDARY',
        attackBonus: 490,
        speedBonus: 0.13,
        priceGem: 3000,
        image: '/assets/images/items/weapons/wea21414ons_sprite.webp',
        atlasFrame: 'wea21414ons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Древний артефакт, способный предсказывать движения врага.',
    },
    daggers_emerald: {
        id: 'daggers_emerald',
        name: 'Клинки Изумрудного Убийцы',
        requiredLevel: 55,
        rarity: 'LEGENDARY',
        attackBonus: 447,
        speedBonus: 0.2,
        priceGem: 3500,
        image: '/assets/images/items/weapons/wea14431413pons_sheet.webp',
        atlasFrame: 'wea14431413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Изумрудное сияние этих клинков — последнее, что видят враги.',
    },

    // MYTHIC - Уровень 65-80
    claws_ice_fire: {
        id: 'claws_ice_fire',
        name: 'Когти Ледяного Пламени',
        requiredLevel: 64,
        rarity: 'MYTHIC',
        attackBonus: 720,
        speedBonus: 0.3,
        priceGem: 4000,
        image: '/assets/images/items/weapons/eaons_sprite.webp',
        atlasFrame: 'eaons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Смертоносное сочетание абсолютного холода и испепеляющего огня.',
    },
    staff_sun_burst: {
        id: 'staff_sun_burst',
        name: 'Жезл Солнечного Всплеска',
        requiredLevel: 69,
        rarity: 'MYTHIC',
        attackBonus: 758,
        speedBonus: 0.14,
        priceGem: 4500,
        image: '/assets/images/items/weapons/wea2114ons_sprite.webp',
        atlasFrame: 'wea2114ons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Извергает потоки чистой солнечной энергии.',
    },
    staff_galaxy: {
        id: 'staff_galaxy',
        name: 'Скипетр Межзвездного Странника',
        requiredLevel: 66,
        rarity: 'MYTHIC',
        attackBonus: 735,
        critBonus: 0.12,
        priceGem: 5000,
        image: '/assets/images/items/weapons/wea1431413pons_sheet.webp',
        atlasFrame: 'wea1431413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Внутри этого скипетра рождаются и гибнут целые миры.',
    },
    sword_moon_glow: {
        id: 'sword_moon_glow',
        name: 'Клинок Лунного Сияния',
        requiredLevel: 71,
        rarity: 'MYTHIC',
        attackBonus: 773,
        critBonus: 0.10,
        priceGem: 5500,
        image: '/assets/images/items/weapons/wea11ons_sprite.webp',
        atlasFrame: 'wea11ons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Призрачное сияние этого меча игнорирует любую броню.',
    },
    axe_ice: {
        id: 'axe_ice',
        name: 'Ледяной Жнец Душ',
        requiredLevel: 75,
        rarity: 'MYTHIC',
        attackBonus: 803,
        critBonus: 0.1,
        priceGem: 6000,
        image: '/assets/images/items/weapons/axe.webp',
        atlasFrame: 'axe.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Его прикосновение замораживает саму душу противника.',
    },
    staff_skull_green: {
        id: 'staff_skull_green',
        name: 'Посох Повелителя Некрополя',
        requiredLevel: 78,
        rarity: 'MYTHIC',
        attackBonus: 825,
        speedBonus: 0.15,
        priceGem: 6500,
        image: '/assets/images/items/weapons/wea1441413pons_sheet.webp',
        atlasFrame: 'wea1441413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Зеленое пламя этого посоха питается страхом врагов.',
    },
    sword_hell: {
        id: 'sword_hell',
        name: 'Меч Преисподней',
        requiredLevel: 80,
        rarity: 'MYTHIC',
        attackBonus: 840,
        critBonus: 0.15,
        priceGem: 7200,
        image: '/assets/images/items/weapons/fire_magic_sword.webp',
        atlasFrame: 'fire_magic_sword.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Клинок, выкованный из застывшей ярости огненного демона.',
    },
    axe_chaos: {
        id: 'axe_chaos',
        name: 'Секира Первородного Хаоса',
        requiredLevel: 73,
        rarity: 'MYTHIC',
        attackBonus: 788,
        critBonus: 0.12,
        priceGem: 8000,
        image: '/assets/images/items/weapons/weap231414ons_sprite.webp',
        atlasFrame: 'weap231414ons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Воплощение разрушительной силы первобытного хаоса.',
    },
};
