import { IEquipmentStats } from './types';

export const weapons: Record<string, IEquipmentStats> = {
    // COMMON - Уровень 1-5
    sling_leather: {
        id: 'sling_leather',
        name: 'Кожаная Праща',
        rarity: 'COMMON',
        priceGold: 200,
        requiredLevel: 1,
        attackBonus: 32,
        image: '/assets/images/items/weapons/sling.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простое метательное оружие из полоски кожи.',
    },
    // Стартовое оружие (id: stick — выдаётся в начале игры)
    stick: {
        id: 'stick',
        name: 'Бамбуковая Палка',
        rarity: 'COMMON',
        priceGold: 100,
        requiredLevel: 1,
        attackBonus: 32,
        image: '/assets/images/items/weapons/stick.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простая бамбуковая палка. Не самое грозное оружие, но с чего-то надо начинать.',
    },
    stick_oak: {
        id: 'stick_oak',
        name: 'Дубовый Посох',
        speedBonus: 0.05,
        rarity: 'COMMON',
        priceGold: 300,
        requiredLevel: 2,
        attackBonus: 33,
        image: '/assets/images/items/weapons/staff.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простой деревянный посох для начинающих магов.',
    },

    pan_master: {
        id: 'pan_master',
        name: 'Чугунная Сковорода',
        rarity: 'COMMON',
        priceGold: 400,
        requiredLevel: 3,
        attackBonus: 35,
        image: '/assets/images/items/weapons/pan.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Тяжелая, надежная и отлично звонит при ударе.',
    },
    // RARE - Уровень 10-20
    sword_broken: {
        id: 'sword_broken',
        name: 'Обломок Катаны',
        speedBonus: 0.08,
        rarity: 'RARE',
        priceGold: 2000,
        requiredLevel: 10,
        attackBonus: 84,
        image: '/assets/images/items/weapons/broken_sword.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Даже в сломанном виде эта сталь остается невероятно острой.',
    },
    dagger_rusty: {
        id: 'dagger_rusty',
        name: 'Ржавый Тесак',
        critBonus: 0.03,
        rarity: 'RARE',
        priceGold: 3500,
        requiredLevel: 10,
        attackBonus: 84,
        image: '/assets/images/items/weapons/rusty_dagger.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Старое лезвие, побитое временем и ржавчиной.',
    },
    dagger_bone: {
        id: 'dagger_bone',
        name: 'Клык Кровавого Жнеца',
        critBonus: 0.03,
        rarity: 'RARE',
        priceGold: 6000,
        requiredLevel: 15,
        attackBonus: 96,
        image: '/assets/images/items/weapons/wa11413pons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Костяной кинжал с навершием в виде черепа.',
    },
    staff_willow: {
        id: 'staff_willow',
        name: 'Ивовый Жезл Очищения',
        speedBonus: 0.07,
        rarity: 'RARE',
        priceGold: 8000,
        requiredLevel: 15,
        attackBonus: 96,
        image: '/assets/images/items/weapons/staff.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Жезл из ветви священной ивы, наполненный энергией природы.',
    },
    dagger_ritual: {
        id: 'dagger_ritual',
        name: 'Кинжал Забытых Предков',
        critBonus: 0.04,
        rarity: 'RARE',
        priceGold: 10000,
        requiredLevel: 15,
        attackBonus: 96,
        image: '/assets/images/items/weapons/wa141413pons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Древнее костяное лезвие с магическими рунами.',
    },
    bow_composite: {
        id: 'bow_composite',
        name: 'Композитный Лук Волка',
        critBonus: 0.03,
        speedBonus: 0.05,
        rarity: 'RARE',
        priceGold: 18000,
        requiredLevel: 20,
        attackBonus: 108,
        image: '/assets/images/items/weapons/bow.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Эргономичный лук, обеспечивающий высокую точность стрельбы.',
    },
    axe_iron: {
        id: 'axe_iron',
        name: 'Секира Лесного Ополченца',
        rarity: 'RARE',
        priceGold: 25000,
        requiredLevel: 20,
        attackBonus: 108,
        image: '/assets/images/items/weapons/wa1441413pons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простой, но надежный топор для защиты своего дома.',
    },

    // EPIC - Уровень 25-45
    katana_shadow: {
        id: 'katana_shadow',
        name: 'Катана Тени',
        speedBonus: 0.1,
        rarity: 'EPIC',
        priceGem: 300,
        requiredLevel: 25,
        attackBonus: 180,
        image: '/assets/images/items/weapons/a113ons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Клинок, который практически не виден в темноте.',
    },
    katana_steel: {
        id: 'katana_steel',
        name: 'Стальная Катана',
        speedBonus: 0.10,
        rarity: 'EPIC',
        priceGem: 350,
        requiredLevel: 27,
        attackBonus: 187,
        image: '/assets/images/items/weapons/a1ons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Классическое оружие, доведенное до совершенства.',
    },
    katana_blood: {
        id: 'katana_blood',
        name: 'Катана Кровавой Луны',
        critBonus: 0.05,
        rarity: 'EPIC',
        priceGem: 420,
        requiredLevel: 30,
        attackBonus: 198,
        image: '/assets/images/items/weapons/a13ons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Её лезвие жаждет битвы так же сильно, как и её владелец.',
    },
    mace_justice: {
        id: 'mace_justice',
        name: 'Булава Правосудия',
        rarity: 'EPIC',
        priceGem: 480,
        requiredLevel: 32,
        attackBonus: 205,
        image: '/assets/images/items/weapons/a113pons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Каждый удар этой булавы несет в себе тяжесть закона.',
    },
    staff_shadow: {
        id: 'staff_shadow',
        name: 'Посох Теневого Мага',
        speedBonus: 0.10,
        rarity: 'EPIC',
        priceGem: 560,
        requiredLevel: 35,
        attackBonus: 216,
        image: '/assets/images/items/weapons/void_staff.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Позволяет манипулировать энергией тени.',
    },
    daggers_assassin: {
        id: 'daggers_assassin',
        name: 'Кинжалы Убийцы',
        speedBonus: 0.15,
        rarity: 'EPIC',
        priceGem: 600,
        requiredLevel: 35,
        attackBonus: 216,
        image: '/assets/images/items/weapons/daggers.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Пара быстрых клинков для тех, кто не привык ждать.',
    },
    axe_executioner: {
        id: 'axe_executioner',
        name: 'Секира Палача',
        rarity: 'EPIC',
        priceGem: 700,
        requiredLevel: 37,
        attackBonus: 223,
        image: '/assets/images/items/weapons/a1113pons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Тяжелый топор, предназначенный для одного решающего удара.',
    },
    flail_guardian: {
        id: 'flail_guardian',
        name: 'Моргенштерн Стража',
        rarity: 'EPIC',
        priceGem: 800,
        requiredLevel: 40,
        attackBonus: 234,
        image: '/assets/images/items/weapons/a11413pons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Шипастый шар на цепи — кошмар любого щитоносца.',
    },
    sword_silver: {
        id: 'sword_silver',
        name: 'Меч Серебряного Рыцаря',
        rarity: 'EPIC',
        priceGem: 900,
        requiredLevel: 42,
        attackBonus: 241,
        image: '/assets/images/items/weapons/moon_sword.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Благородный клинок из лучшей стали империи.',
    },
    axe_veteran: {
        id: 'axe_veteran',
        name: 'Боевой Топор Ветерана',
        rarity: 'EPIC',
        priceGem: 1000,
        requiredLevel: 43,
        attackBonus: 245,
        image: '/assets/images/items/weapons/heavy_war_axe.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Оружие, прошедшее через сотни сражений.',
    },
    weapon_moon_sword: {
        id: 'weapon_moon_sword',
        name: 'Эпический Меч Луны',
        critBonus: 0.08,
        rarity: 'EPIC',
        priceGem: 1200,
        requiredLevel: 45,
        attackBonus: 252,
        image: '/assets/images/items/weapons/moon_sword.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Овеянный легендами клинок, вобравший в себя холодное сияние ночной луны.',
    },

    // LEGENDARY - Уровень 50-60
    bow_griffin: {
        id: 'bow_griffin',
        name: 'Лук Золотого Грифона',
        critBonus: 0.03,
        speedBonus: 0.05,
        rarity: 'LEGENDARY',
        priceGem: 1500,
        requiredLevel: 50,
        attackBonus: 420,
        image: '/assets/images/items/weapons/bow.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Тетива этого лука поет, когда стрела летит точно в цель.',
    },
    staff_celestial: {
        id: 'staff_celestial',
        name: 'Жезл Небесного Ока',
        speedBonus: 0.12,
        rarity: 'LEGENDARY',
        priceGem: 2000,
        requiredLevel: 52,
        attackBonus: 431,
        image: '/assets/images/items/weapons/wea231414ons_sprite.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Направляет энергию чистого света на противников.',
    },
    hammer_phoenix: {
        id: 'hammer_phoenix',
        name: 'Молот Пылающего Феникса',
        rarity: 'LEGENDARY',
        priceGem: 2500,
        requiredLevel: 55,
        attackBonus: 447,
        image: '/assets/images/items/weapons/phoenix_hammer.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Удары этого молота вызывают вспышки священного огня.',
    },
    staff_gold: {
        id: 'staff_gold',
        name: 'Посох Золотого Оракула',
        speedBonus: 0.13,
        rarity: 'LEGENDARY',
        priceGem: 3000,
        requiredLevel: 57,
        attackBonus: 458,
        image: '/assets/images/items/weapons/wea21414ons_sprite.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Древний артефакт, способный предсказывать движения врага.',
    },
    daggers_emerald: {
        id: 'daggers_emerald',
        name: 'Клинки Изумрудного Убийцы',
        speedBonus: 0.2,
        rarity: 'LEGENDARY',
        priceGem: 3500,
        requiredLevel: 60,
        attackBonus: 474,
        image: '/assets/images/items/weapons/wea14431413pons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Изумрудное сияние этих клинков — последнее, что видят враги.',
    },

    // MYTHIC - Уровень 65-80
    claws_ice_fire: {
        id: 'claws_ice_fire',
        name: 'Когти Ледяного Пламени',
        speedBonus: 0.3,
        rarity: 'MYTHIC',
        priceGem: 4000,
        requiredLevel: 65,
        attackBonus: 728,
        image: '/assets/images/items/weapons/eaons_sprite.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Смертоносное сочетание абсолютного холода и испепеляющего огня.',
    },
    staff_sun_burst: {
        id: 'staff_sun_burst',
        name: 'Жезл Солнечного Всплеска',
        speedBonus: 0.14,
        rarity: 'MYTHIC',
        priceGem: 4500,
        requiredLevel: 67,
        attackBonus: 743,
        image: '/assets/images/items/weapons/wea2114ons_sprite.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Извергает потоки чистой солнечной энергии.',
    },
    staff_galaxy: {
        id: 'staff_galaxy',
        name: 'Скипетр Межзвездного Странника',
        critBonus: 0.12,
        rarity: 'MYTHIC',
        priceGem: 5000,
        requiredLevel: 70,
        attackBonus: 765,
        image: '/assets/images/items/weapons/wea1431413pons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Внутри этого скипетра рождаются и гибнут целые миры.',
    },
    sword_moon_glow: {
        id: 'sword_moon_glow',
        name: 'Клинок Лунного Сияния',
        rarity: 'MYTHIC',
        priceGem: 5500,
        requiredLevel: 72,
        attackBonus: 780,
        image: '/assets/images/items/weapons/wea11ons_sprite.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Призрачное сияние этого меча игнорирует любую броню.',
    },
    axe_ice: {
        id: 'axe_ice',
        name: 'Ледяной Жнец Душ',
        critBonus: 0.1,
        rarity: 'MYTHIC',
        priceGem: 6000,
        requiredLevel: 74,
        attackBonus: 795,
        image: '/assets/images/items/weapons/axe.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Его прикосновение замораживает саму душу противника.',
    },
    staff_skull_green: {
        id: 'staff_skull_green',
        name: 'Посох Повелителя Некрополя',
        speedBonus: 0.15,
        rarity: 'MYTHIC',
        priceGem: 6500,
        requiredLevel: 76,
        attackBonus: 810,
        image: '/assets/images/items/weapons/wea1441413pons_sheet.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Зеленое пламя этого посоха питается страхом врагов.',
    },
    sword_hell: {
        id: 'sword_hell',
        name: 'Меч Преисподней',
        critBonus: 0.15,
        rarity: 'MYTHIC',
        priceGem: 7200,
        requiredLevel: 78,
        attackBonus: 825,
        image: '/assets/images/items/weapons/fire_magic_sword.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Клинок, выкованный из застывшей ярости огненного демона.',
    },
    axe_chaos: {
        id: 'axe_chaos',
        name: 'Секира Первородного Хаоса',
        rarity: 'MYTHIC',
        priceGem: 8000,
        requiredLevel: 80,
        attackBonus: 840,
        image: '/assets/images/items/weapons/weap231414ons_sprite.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Воплощение разрушительной силы первобытного хаоса.',
    },
};
