import { IEquipmentStats } from './types';

export const weapons: Record<string, IEquipmentStats> = {
    // COMMON - Самое простое
    stick_oak: {
        id: 'stick_oak',
        name: 'Дубовый Посох',
        attackBonus: 12,
        rarity: 'COMMON',
        priceGold: 400,
        image: '/assets/images/items/weapons/staff.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простой деревянный посох для начинающих магов.',
    },
    club_wooden: {
        id: 'club_wooden',
        name: 'Тяжелая Дубина',
        attackBonus: 20,
        rarity: 'COMMON',
        priceGold: 500,
        image: '/assets/images/items/weapons/stick.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Грубый кусок дерева, способный проломить череп.',
    },
    pan_master: {
        id: 'pan_master',
        name: 'Чугунная Сковорода',
        attackBonus: 15,
        rarity: 'COMMON',
        priceGold: 300,
        image: '/assets/images/items/weapons/pan.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Тяжелая, надежная и отлично звонит при ударе.',
    },
    sling_leather: {
        id: 'sling_leather',
        name: 'Кожаная Праща',
        attackBonus: 10,
        rarity: 'COMMON',
        priceGold: 200,
        image: '/assets/images/items/weapons/sling.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простое метательное оружие из полоски кожи.',
    },

    // RARE - Кость и железо
    sword_broken: {
        id: 'sword_broken',
        name: 'Обломок Катаны',
        attackBonus: 25,
        rarity: 'RARE',
        priceGold: 1500,
        image: '/assets/images/items/weapons/broken_sword.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Даже в сломанном виде эта сталь остается невероятно острой.',
    },
    dagger_rusty: {
        id: 'dagger_rusty',
        name: 'Ржавый Тесак',
        attackBonus: 30,
        rarity: 'RARE',
        priceGold: 2000,
        image: '/assets/images/items/weapons/rusty_dagger.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Старое лезвие, побитое временем и ржавчиной.',
    },
    dagger_ritual: {
        id: 'dagger_ritual',
        name: 'Кинжал Забытых Предков',
        attackBonus: 40,
        rarity: 'RARE',
        priceGold: 3800,
        image: '/assets/images/items/weapons/wa141413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Древнее костяное лезвие с магическими рунами.',
    },
    dagger_bone: {
        id: 'dagger_bone',
        name: 'Клык Кровавого Жнеца',
        attackBonus: 35,
        rarity: 'RARE',
        priceGold: 2500,
        image: '/assets/images/items/weapons/wa11413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Костяной кинжал с навершием в виде черепа.',
    },
    axe_iron: {
        id: 'axe_iron',
        name: 'Секира Лесного Ополченца',
        attackBonus: 45,
        rarity: 'RARE',
        priceGold: 4500,
        image: '/assets/images/items/weapons/wa1441413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Простой, но надежный топор для защиты своего дома.',
    },

    // EPIC - Мастерская ковка
    katana_steel: {
        id: 'katana_steel',
        name: 'Стальная Катана',
        attackBonus: 90,
        rarity: 'EPIC',
        priceGem: 500,
        image: '/assets/images/items/weapons/a1ons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Классическое оружие, доведенное до совершенства.',
    },
    katana_blood: {
        id: 'katana_blood',
        name: 'Катана Кровавой Луны',
        attackBonus: 95,
        critBonus: 0.05,
        rarity: 'EPIC',
        priceGem: 550,
        image: '/assets/images/items/weapons/a13ons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Её лезвие жаждет битвы так же сильно, как и её владелец.',
    },
    katana_shadow: {
        id: 'katana_shadow',
        name: 'Катана Тени',
        attackBonus: 85,
        speedBonus: 0.1,
        rarity: 'EPIC',
        priceGem: 450,
        image: '/assets/images/items/weapons/a113ons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Клинок, который практически не виден в темноте.',
    },
    axe_executioner: {
        id: 'axe_executioner',
        name: 'Секира Палача',
        attackBonus: 110,
        rarity: 'EPIC',
        priceGem: 650,
        image: '/assets/images/items/weapons/a1113pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Тяжелый топор, предназначенный для одного решающего удара.',
    },
    mace_justice: {
        id: 'mace_justice',
        name: 'Булава Правосудия',
        attackBonus: 100,
        rarity: 'EPIC',
        priceGem: 600,
        image: '/assets/images/items/weapons/a113pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Каждый удар этой булавы несет в себе тяжесть закона.',
    },
    flail_guardian: {
        id: 'flail_guardian',
        name: 'Моргенштерн Стража',
        attackBonus: 115,
        rarity: 'EPIC',
        priceGem: 700,
        image: '/assets/images/items/weapons/a11413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Шипастый шар на цепи — кошмар любого щитоносца.',
    },
    daggers_assassin: {
        id: 'daggers_assassin',
        name: 'Кинжалы Убийцы',
        attackBonus: 90,
        speedBonus: 0.15,
        rarity: 'EPIC',
        priceGem: 700,
        image: '/assets/images/items/weapons/daggers.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Пара быстрых клинков для тех, кто не привык ждать.',
    },
    axe_veteran: {
        id: 'axe_veteran',
        name: 'Боевой Топор Ветерана',
        attackBonus: 125,
        rarity: 'EPIC',
        priceGem: 850,
        image: '/assets/images/items/weapons/heavy_war_axe.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Оружие, прошедшее через сотни сражений.',
    },
    sword_silver: {
        id: 'sword_silver',
        name: 'Меч Серебряного Рыцаря',
        attackBonus: 120,
        rarity: 'EPIC',
        priceGem: 800,
        image: '/assets/images/items/weapons/moon_sword.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Благородный клинок из лучшей стали империи.',
    },
    staff_shadow: {
        id: 'staff_shadow',
        name: 'Посох Теневого Мага',
        attackBonus: 105,
        rarity: 'EPIC',
        priceGem: 750,
        image: '/assets/images/items/weapons/void_staff.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Позволяет манипулировать энергией тени.',
    },

    // LEGENDARY - Высшее качество
    bow_griffin: {
        id: 'bow_griffin',
        name: 'Лук Золотого Грифона',
        attackBonus: 230,
        rarity: 'LEGENDARY',
        priceGem: 1600,
        image: '/assets/images/items/weapons/bow.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Тетива этого лука поет, когда стрела летит точно в цель.',
    },
    hammer_phoenix: {
        id: 'hammer_phoenix',
        name: 'Молот Пылающего Феникса',
        attackBonus: 250,
        rarity: 'LEGENDARY',
        priceGem: 1800,
        image: '/assets/images/items/weapons/phoenix_hammer.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Удары этого молота вызывают вспышки священного огня.',
    },
    daggers_emerald: {
        id: 'daggers_emerald',
        name: 'Клинки Изумрудного Убийцы',
        attackBonus: 280,
        speedBonus: 0.2,
        rarity: 'LEGENDARY',
        priceGem: 2200,
        image: '/assets/images/items/weapons/wea14431413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Изумрудное сияние этих клинков — последнее, что видят враги.',
    },
    staff_celestial: {
        id: 'staff_celestial',
        name: 'Жезл Небесного Ока',
        attackBonus: 240,
        rarity: 'LEGENDARY',
        priceGem: 2000,
        image: '/assets/images/items/weapons/wea231414ons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Направляет энергию чистого света на противников.',
    },
    staff_gold: {
        id: 'staff_gold',
        name: 'Посох Золотого Оракула',
        attackBonus: 260,
        rarity: 'LEGENDARY',
        priceGem: 2100,
        image: '/assets/images/items/weapons/wea21414ons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Древний артефакт, способный предсказывать движения врага.',
    },

    // MYTHIC - Божественные артефакты
    axe_ice: {
        id: 'axe_ice',
        name: 'Ледяной Жнец Душ',
        attackBonus: 550,
        critBonus: 0.1,
        rarity: 'MYTHIC',
        priceGem: 4500,
        image: '/assets/images/items/weapons/axe.webp',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Его прикосновение замораживает саму душу противника.',
    },
    claws_ice_fire: {
        id: 'claws_ice_fire',
        name: 'Когти Ледяного Пламени',
        attackBonus: 500,
        speedBonus: 0.3,
        rarity: 'MYTHIC',
        priceGem: 4200,
        image: '/assets/images/items/weapons/eaons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Смертоносное сочетание абсолютного холода и испепеляющего огня.',
    },
    sword_hell: {
        id: 'sword_hell',
        name: 'Меч Преисподней',
        attackBonus: 600,
        critBonus: 0.15,
        rarity: 'MYTHIC',
        priceGem: 5500,
        image: '/assets/images/items/weapons/fire_magic_sword.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Клинок, выкованный из застывшей ярости огненного демона.',
    },
    sword_moon_glow: {
        id: 'sword_moon_glow',
        name: 'Клинок Лунного Сияния',
        attackBonus: 540,
        rarity: 'MYTHIC',
        priceGem: 4800,
        image: '/assets/images/items/weapons/wea11ons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Призрачное сияние этого меча игнорирует любую броню.',
    },
    staff_galaxy: {
        id: 'staff_galaxy',
        name: 'Скипетр Межзвездного Странника',
        attackBonus: 520,
        critBonus: 0.2,
        rarity: 'MYTHIC',
        priceGem: 5000,
        image: '/assets/images/items/weapons/wea1431413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Внутри этого скипетра рождаются и гибнут целые миры.',
    },
    staff_skull_green: {
        id: 'staff_skull_green',
        name: 'Посох Повелителя Некрополя',
        attackBonus: 580,
        rarity: 'MYTHIC',
        priceGem: 5200,
        image: '/assets/images/items/weapons/wea1441413pons_sheet.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Зеленое пламя этого посоха питается страхом врагов.',
    },
    staff_sun_burst: {
        id: 'staff_sun_burst',
        name: 'Жезл Солнечного Всплеска',
        attackBonus: 530,
        rarity: 'MYTHIC',
        priceGem: 4600,
        image: '/assets/images/items/weapons/wea2114ons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Извергает потоки чистой солнечной энергии.',
    },
    axe_chaos: {
        id: 'axe_chaos',
        name: 'Секира Первородного Хаоса',
        attackBonus: 650,
        rarity: 'MYTHIC',
        priceGem: 6500,
        image: '/assets/images/items/weapons/weap231414ons_sprite.png',
        mainTab: 'ARSENAL',
        subTab: 'WEAPONS',
        desc: 'Воплощение разрушительной силы первобытного хаоса.',
    },
};
