import { ClanData } from './ClanShared';

export const MOCK_CLANS: ClanData[] = [
    {
        id: 'clan_1',
        name: 'СЫНЫ ФЕНРИРА',
        motto: 'Вой наших клинков сокрушит любого врага!',
        level: 8,
        membersCount: 42,
        maxMembers: 50,
        totalTrophies: 34200,
        emblem: 'wolf',
        minTrophies: 1500,
        type: 'OPEN',
        onlineCount: 12,
        xp: 750,
        maxXp: 8000,
        tag: 'PvP / Активный',
        bonus: '+10% Золота',
    },
    {
        id: 'clan_2',
        name: 'ОРДЕН ЗАРЯ',
        motto: 'Свет разгонит тьму дикого леса.',
        level: 12,
        membersCount: 48,
        maxMembers: 50,
        totalTrophies: 48500,
        emblem: 'eagle',
        minTrophies: 3000,
        type: 'INVITE',
        onlineCount: 19,
        xp: 4200,
        maxXp: 12000,
        tag: 'PvE / Рейды',
        bonus: '+15% Опыта',
    },
    {
        id: 'clan_3',
        name: 'ГНЕВ ДРАКОНА',
        motto: 'Пламя и пепел — наша общая судьба.',
        level: 15,
        membersCount: 50,
        maxMembers: 50,
        totalTrophies: 58000,
        emblem: 'dragon',
        minTrophies: 4000,
        type: 'CLOSED',
        onlineCount: 25,
        xp: 9800,
        maxXp: 15000,
        tag: 'Хардкор / Топ',
        bonus: '+5% Силы',
    },
    {
        id: 'clan_4',
        name: 'ХРАНИТЕЛИ ЛЕСА',
        motto: 'Дикая природа защищает своих детей.',
        level: 5,
        membersCount: 15,
        maxMembers: 40,
        totalTrophies: 12400,
        emblem: 'fox',
        minTrophies: 0,
        type: 'OPEN',
        onlineCount: 3,
        xp: 350,
        maxXp: 5000,
        tag: 'Казуальный',
        bonus: '+5% Золота',
    },
    {
        id: 'clan_5',
        name: 'СЕРЕБРЯНЫЕ КОГТИ',
        motto: 'Тихий шаг, смертельный удар в ночи.',
        level: 6,
        membersCount: 28,
        maxMembers: 45,
        totalTrophies: 21000,
        emblem: 'tiger',
        minTrophies: 1000,
        type: 'OPEN',
        onlineCount: 7,
        xp: 1200,
        maxXp: 6000,
        tag: 'PvP / Активный',
        bonus: '+8% Опыта',
    },
    {
        id: 'clan_6',
        name: 'МУДРЫЕ СОВЫ',
        motto: 'Знание и стратегия — это величайшая сила.',
        level: 9,
        membersCount: 31,
        maxMembers: 50,
        totalTrophies: 28900,
        emblem: 'owl',
        minTrophies: 2000,
        type: 'INVITE',
        onlineCount: 11,
        xp: 5100,
        maxXp: 9000,
        tag: 'PvE / Общение',
        bonus: '+12% Опыта',
    },
    {
        id: 'clan_7',
        name: 'ЖЕЛЕЗНЫЕ МЕДВЕДИ',
        motto: 'Крепки как скала, верны до самого гроба.',
        level: 7,
        membersCount: 39,
        maxMembers: 50,
        totalTrophies: 26400,
        emblem: 'bear',
        minTrophies: 1200,
        type: 'OPEN',
        onlineCount: 8,
        xp: 3200,
        maxXp: 7000,
        tag: 'Активный / PvE',
        bonus: '+8% Золота',
    },
    {
        id: 'clan_8',
        name: 'ПРАЙД ЛЬВА',
        motto: 'Лидеры по праву рождения и силе.',
        level: 10,
        membersCount: 45,
        maxMembers: 50,
        totalTrophies: 39000,
        emblem: 'lion',
        minTrophies: 2500,
        type: 'INVITE',
        onlineCount: 15,
        xp: 6200,
        maxXp: 10000,
        tag: 'PvP / Турниры',
        bonus: '+10% Золота',
    },
    {
        id: 'clan_9',
        name: 'БРОДЯЧИЕ ВОЛКИ',
        motto: 'Одиночки собираются в сильную стаю.',
        level: 3,
        membersCount: 8,
        maxMembers: 30,
        totalTrophies: 5200,
        emblem: 'wolf',
        minTrophies: 0,
        type: 'OPEN',
        onlineCount: 2,
        xp: 450,
        maxXp: 3000,
        tag: 'Для новичков',
        bonus: '+5% Опыта',
    },
    {
        id: 'clan_10',
        name: 'ЧЕРНОЕ СОЛНЦЕ',
        motto: 'Затмение принесет наш вечный триумф.',
        level: 14,
        membersCount: 49,
        maxMembers: 50,
        totalTrophies: 54000,
        emblem: 'dragon',
        minTrophies: 3500,
        type: 'INVITE',
        onlineCount: 21,
        xp: 11000,
        maxXp: 14000,
        tag: 'Хардкор / PvP',
        bonus: '+12% Золота',
    },
];

export const DEFAULT_MOCK_MEMBERS = [
    {
        name: 'Алексей',
        role: 'OFFICER' as const,
        trophies: 4200,
        lastSeen: 'В сети',
        isOnline: true,
        avatar: 'sprite:sprite-avatar avatar-pos-3',
        contribution: 250,
        level: 28,
    },
    {
        name: 'Дмитрий',
        role: 'MEMBER' as const,
        trophies: 2100,
        lastSeen: '1д назад',
        isOnline: false,
        avatar: 'sprite:sprite-avatar avatar-pos-4',
        contribution: 120,
        level: 15,
    },
    {
        name: 'София',
        role: 'OFFICER' as const,
        trophies: 5400,
        lastSeen: 'В сети',
        isOnline: true,
        avatar: 'sprite:sprite-avatar avatar-pos-7',
        contribution: 410,
        level: 32,
    },
    {
        name: 'Артур',
        role: 'MEMBER' as const,
        trophies: 950,
        lastSeen: '5ч назад',
        isOnline: false,
        avatar: 'sprite:sprite-avatar avatar-pos-6',
        contribution: 50,
        level: 8,
    },
    {
        name: 'Елена',
        role: 'MEMBER' as const,
        trophies: 1600,
        lastSeen: 'В сети',
        isOnline: true,
        avatar: 'sprite:sprite-avatar avatar-pos-9',
        contribution: 180,
        level: 12,
    }
];

