// Settings Window Localization Dictionary

export const settingsTranslations = {
    RU: {
        title: "НАСТРОЙКИ",
        audioSettings: "НАСТРОЙКИ ЗВУКА",
        musicVolume: "ГРОМКОСТЬ МУЗЫКИ",
        sfxVolume: "ГРОМКОСТЬ ЭФФЕКТОВ",
        on: "ВКЛ",
        off: "ВЫКЛ",
        account: "АККАУНТ",
        playerId: "ID ИГРОКА",
        copy: "КОПИРОВАТЬ",
        copied: "ОК!",
        language: "ЯЗЫК / LANGUAGE",
        vkCommunity: "🌐 МЫ ВКОНТАКТЕ",
        toFavorites: "⭐ В ИЗБРАННОЕ",
        replayIntro: "🎬 ПОВТОРИТЬ ИНТРО",
        wipeProgress: "🗑️ ПОЛНЫЙ ВАЙП ПРОГРЕССА",
        clearChat: "🧹 АДМИН: ОЧИСТИТЬ ВЕСЬ ЧАТ",
        confirmWipe: "⚠️ ТОЧНО СБРОСИТЬ ВСЁ?",
        confirmClear: "⚠️ ТОЧНО УДАЛИТЬ ЧАТ?",
        connectedVk: "🔗 ПРИВЯЗАНО К ВКОНТАКТЕ",
        mediaPlayer: "МЕДИАПЛЕЕР",
        nowPlaying: "СЕЙЧАС ИГРАЕТ",
        status: "СТАТУС ИГРЫ",
        online: "СЕТЬ СТАБИЛЬНА",
        // Advanced settings block
        graphicsHeader: "ГРАФИКА И ОПТИМИЗАЦИЯ",
        fullscreen: "ПОЛНОЭКРАННЫЙ РЕЖИМ",
        showFps: "ОТОБРАЖАТЬ FPS",
        powerSaving: "ЭНЕРГОСБЕРЕЖЕНИЕ (30 FPS)",
        pushNotifications: "PUSH-УВЕДОМЛЕНИЯ",
        uiAnimations: "АНИМАЦИИ ИНТЕРФЕЙСА",
        glowAura: "СВЕЧЕНИЕ АУРЫ (GLOW)",
        particleEffects: "ЭФФЕКТЫ ЧАСТИЦ В БОЮ",
        low: "НИЗКОЕ",
        high: "ВЫСОКОЕ",
    },
    EN: {
        title: "SETTINGS",
        audioSettings: "AUDIO SETTINGS",
        musicVolume: "MUSIC VOLUME",
        sfxVolume: "SFX VOLUME",
        on: "ON",
        off: "OFF",
        account: "ACCOUNT",
        playerId: "PLAYER ID",
        copy: "COPY",
        copied: "OK!",
        language: "LANGUAGE / ЯЗЫК",
        vkCommunity: "🌐 VK COMMUNITY",
        toFavorites: "⭐ TO FAVORITES",
        replayIntro: "🎬 REPLAY INTRO",
        wipeProgress: "WIPE ALL PROGRESS",
        clearChat: "🧹 ADMIN: CLEAR ALL CHAT",
        confirmWipe: "⚠️ CONFIRM FULL RESET?",
        confirmClear: "⚠️ CONFIRM CLEAR CHAT?",
        connectedVk: "🔗 LINKED TO VKONTAKTE",
        mediaPlayer: "MEDIA PLAYER",
        nowPlaying: "NOW PLAYING",
        status: "GAME STATUS",
        online: "STABLE CONNECTION",
        // Advanced settings block
        graphicsHeader: "GRAPHICS & OPTIMIZATION",
        fullscreen: "FULLSCREEN MODE",
        showFps: "SHOW FPS",
        powerSaving: "POWER SAVING (30 FPS)",
        pushNotifications: "PUSH NOTIFICATIONS",
        uiAnimations: "UI ANIMATIONS",
        glowAura: "GLOW AURA (GLOW)",
        particleEffects: "BATTLE PARTICLE EFFECTS",
        low: "LOW",
        high: "HIGH",
    }
};
